20150613115016: Traceback: Traceback (most recent call last):
  File "main2.py", line 130, in main
    text=irc.recv(2040)
  File "C:\Python27\lib\ssl.py", line 241, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 160, in read
    return self._sslobj.read(len)
error: [Errno 10054] An existing connection was forcibly closed by the remote host

20150613205557: Establishing connection to [irc.horse]
20150613205600: :cadance.canternet.org NOTICE Auth :*** Looking up your hostname...
:cadance.canternet.org NOTICE Auth :*** Found your hostname (host-78-149-0-145.as13285.net)

20150613205600: PING :]M{~s[Rgd_
:cadance.canternet.org NOTICE sleumasBot :*** If you are having problems connecting due to ping timeouts, please type /quote PONG ]M{~s[Rgd_ or /raw PONG ]M{~s[Rgd_ now.

20150613205600: Ping Request Responded to Successfully
20150613205601: :cadance.canternet.org NOTICE Auth :Welcome to Canternet!
:cadance.canternet.org 001 sleumasBot :Welcome to the Canternet IRC Network sleumasBot!sleumasBot@host-78-149-0-145.as13285.net
:cadance.canternet.org 002 sleumasBot :Your host is cadance.canternet.org, running version InspIRCd-2.0
:cadance.canternet.org 003 sleumasBot :This server was created 01:24:01 May 12 2015
:cadance.canternet.org 004 sleumasBot cadance.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:cadance.canternet.org 005 sleumasBot AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:cadance.canternet.org 005 sleumasBot KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150613205601: Ping Request Responded to Successfully
20150613205601: 
:cadance.canternet.org 005 sleumasBot SSL=0.0.0.0:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:cadance.canternet.org 042 sleumasBot 142ABWK3L :your unique ID
:cadance.canternet.org 375 sleumasBot :cadance.canternet.org message of the day
:cadance.canternet.org 372 sleumasBot :-                                                 Y
:cadance.canternet.org 372 sleumasBot :-                                                Yj
:cadance.canternet.org 372 sleumasBot :-                                              jYY
:cadance.canternet.org 372 sleumasBot :-                                      #YYTYYYYYYaT   B
:cadance.canternet.org 372 sleumasBot :-                                   zzFYYYYY        J#a
:cadance.canternet.org 372 sleumasBot :-                                 JDsJaF     EEBBHE6YYJ Y
:cadance.canternet.org 372 sleumasBot :-                                TDTTJTJ  EHFFGFGFGFFBE  Yz
:cadance.canternet.org 372 sleumasBot :-                               7 GTGTJTLEHBFGGRGGFFFGFFE
20150613205601: 
:cadance.canternet.org 372 sleumasBot :-                               Y RTnJTJTTYYEEFFGB  HFGFFBE
:cadance.canternet.org 372 sleumasBot :-                              x  RYTTJTJTHTTYY BFLYY EHBFBE
:cadance.canternet.org 372 sleumasBot :-                              1 EHYYTTJTsa    GE ZYPEE  EHEE
:cadance.canternet.org 372 sleumasBot :-                              s HBFYYJTas    EEEEYYJ E    EE
:cadance.canternet.org 372 sleumasBot :-                              1 EFFBYTTJx   zY  E TJ E
:cadance.canternet.org 372 sleumasBot :-        7jYTYTYYYT1            Y HFFTYYJa   1  EEYT@ E
:cadance.canternet.org 372 sleumasBot :-      nYYYYYYY     YT          z  HFFHYYJ#   aY EYTT E
:cadance.canternet.org 372 sleumasBot :-    1TYYYYYY  YEEE   YY         Y YBFBHET#Y   GDsTTJTRG
:cadance.canternet.org 372 sleumasBot :-   7YYYYYY  EBFFFFBBE  YJ       7Y FFGFYTJz#x YTJTJTeTB
:cadance.canternet.org 372 sleumasBot :-   TYYYYYY EFGRRRFFFFHE  x       x  HFFYYTTaa#asJJJFJB
:cadance.canternet.org 372 sleumasBot :-  nYYYYYY 1FGDRGFBHHEBHE  5FBFY   T  FFFYTTFis1zxLB
20150613205601: 
:cadance.canternet.org 372 sleumasBot :-  1YYYYYY EFDRGBE     EEDJJJTaa#F J  BFEYTTF
:cadance.canternet.org 372 sleumasBot :-  TYYYYYY EGRRFJ       GT JTJTaJsaJ  BBYTTJ8
:cadance.canternet.org 372 sleumasBot :-  YYYYYYY EFDGB        sTTTaJJJaTa  EBEYTJTL
:cadance.canternet.org 372 sleumasBot :-  7YYYYYY 0FRRB       FsYYsJaTJTJT EBBYTJJa8
:cadance.canternet.org 372 sleumasBot :-  7YYYYYY  BGGFE      DJTTJJTJTTT EHEYTJTaJB
:cadance.canternet.org 372 sleumasBot :-   YYYYYYY EFRFB       # JsTJTTJEEYYYYTJaJs
:cadance.canternet.org 372 sleumasBot :-   jYYYYYY  FGRFL      0aaJJTRTTTTTTTJTaJzG
:cadance.canternet.org 372 sleumasBot :-    7YYYYYY EFGFE      P#JJT1TTTTTJTJTTJX
:cadance.canternet.org 372 sleumasBot :-     jYYYYY  BGGF@      JJTTeneGTJJJTTRK
:cadance.canternet.org 372 sleumasBot :-      jYYYYY EFRFE    jsaTTD71 GTTJTX7nO
:cadance.canternet.org 372 sleumasBot :-       1YYYY  FGGB   BaaTJT7xG JJaJTnj7O
:cadance.canternet.org 372 sleumasBot :-       xYYYYY BRGFE  aaTJTR1jRYJJTJTp1jjZ
:cadance.canternet.org 372 sleumasBot :-       TYYYY  BGDFH GJJaTTLj7 GJTaTTi1zjF
20150613205601: 
:cadance.canternet.org 372 sleumasBot :-       xYYYY  BRRFH FTJJJTn1X FTJTTTRzxxF
:cadance.canternet.org 372 sleumasBot :-  #TTTYYYY   EGGRBE 1JTaJs7j@ iJTJTT8x#7P
:cadance.canternet.org 372 sleumasBot :-   1YYYYY   EFGGBH  #JJTJTn1e eTJJJTRz1zjR
:cadance.canternet.org 372 sleumasBot :-     7sJYYEHFFFBE   ssJJTT571pPTTJTTT71nnF
:cadance.canternet.org 372 sleumasBot :-       EEEEEEHE     zJJTJTR1eRGTJTaTTRXX@G 
:cadance.canternet.org 372 sleumasBot :-                    ZJTJTTR8  GJTJJJTG
:cadance.canternet.org 372 sleumasBot :-                    FGTTJTF    KJTaTJTi
:cadance.canternet.org 372 sleumasBot :- 
:cadance.canternet.org 372 sleumasBot :- /---------------------------------------------------------\
:cadance.canternet.org 372 sleumasBot :- |           Welcome to canternet.org IRC!                 |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Rules: 1) No spamming/flooding                          |
20150613205602: 
:cadance.canternet.org 372 sleumasBot :- |        2) No abusive bots                               |
:cadance.canternet.org 372 sleumasBot :- | For more detailed rules, use the /rules command         |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Ports:                                                  |
:cadance.canternet.org 372 sleumasBot :- |       SSL: 6660-6665                                    |
:cadance.canternet.org 372 sleumasBot :- |       non-SSL: 6666-6669                                |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Official Channels:                                      |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- |       Lobby: #Canternet                                 |
:cadance.canternet.org 372 sleumasBot :- |       Help:  #Help                                      |
20150613205602: 
:cadance.canternet.org 372 sleumasBot :- | For other channels use /list or /msg ALIS list          |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Services:                                               |
:cadance.canternet.org 372 sleumasBot :- |    /msg NickServ help                                   |
:cadance.canternet.org 372 sleumasBot :- |    /msg ChanServ help                                   |
:cadance.canternet.org 372 sleumasBot :- |    /msg MemoServ help                                   |
:cadance.canternet.org 372 sleumasBot :- | For all other services: /msg HelpServ services          |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- \---------------------------------------------------------/
:cadance.canternet.org 376 sleumasBot :End of message of the day.
:cadance.canternet.org 251 sleumasBot :There are 7 users and 1109 invisible on 7 servers
20150613205602: 
:cadance.canternet.org 252 sleumasBot 40 :operator(s) online
:cadance.canternet.org 254 sleumasBot 796 :channels formed
:cadance.canternet.org 255 sleumasBot :I have 484 clients and 2 servers
:cadance.canternet.org 265 sleumasBot :Current Local Users: 484  Max: 1009
:cadance.canternet.org 266 sleumasBot :Current Global Users: 1116  Max: 2151
:cadance.canternet.org 396 sleumasBot Pony-04r97a.as13285.net :is now your displayed host
:sleumasBot!sleumasBot@Pony-04r97a.as13285.net MODE sleumasBot +xi
:cadance.canternet.org NOTICE sleumasBot :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:cadance.canternet.org NOTICE sleumasBot :*** Forwarding PASS to NickServ

20150613205602: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** End of Message(s) of the Day ***
20150613205602: 

20150613205602: :NickServ!NickServ@canternet.org NOTICE sleumasBot :This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
:NickServ!NickServ@canternet.org NOTICE sleumasBot :You have 30 seconds to identify to your nickname before it is changed.
:NickServ!NickServ@canternet.org NOTICE sleumasBot :You are now identified for sleumas2000.
:cadance.canternet.org 900 sleumasBot sleumasBot!sleumasBot@Pony-04r97a.as13285.net sleumas2000 :You are now logged in as sleumas2000
:cadance.canternet.org MODE sleumasBot -x
:cadance.canternet.org 396 sleumasBot my.little.karaoke :is now your displayed host

20150613205606: Connected
20150613205606: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :You are already logged in as sleumas2000.
20150613205606: input: :sleumasBot!sleumasBot@my.little.karaoke JOIN :#Sleu
20150613205606: input: :cadance.canternet.org 332 sleumasBot #Sleu :#Sleu: The awesome Channel
20150613205606: input: :cadance.canternet.org 333 sleumasBot #Sleu sleumas2000 1422522563
20150613205606: input: :cadance.canternet.org 353 sleumasBot = #Sleu :hoofy RedHelper sleumasBot ~sleumas2000 
20150613205607: input: :cadance.canternet.org 366 sleumasBot #Sleu :End of /NAMES list.
20150613205607: input: :ChanServ!ChanServ@canternet.org MODE #Sleu +qo sleumasBot sleumasBot
20150613205613: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :the only thing that's not is the source swticher
20150613205619: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :which in turn feeds to |live
20150613205625: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :so it's giving an error right now
20150613205638: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :|live
20150613205649: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :|np
20150613205704: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :|l
20150613205730: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :that just reads from a file
20150613205735: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :I jut put that in there as dummy names
20150613205753: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :So the bot won't be updated in a while?
20150613205905: input: PING :cadance.canternet.org
20150613205905: input: PING :cadance.canternet.org
20150613205905: Ping Request Responded to Successfully
20150613205905: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613205905: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613205915: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :sorry
20150613205917: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :only 2 days
20150613205920: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :I have DofE
20150613205923: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :It's cool.
20150613205927: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :which is basically a walking thing
20150613205929: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :I can wait.
20150613205945: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :just gonna restart the bot
20150613205948: Establishing connection to [irc.horse]
20150613205952: :cadance.canternet.org NOTICE Auth :*** Looking up your hostname...
:cadance.canternet.org NOTICE Auth :*** Found your hostname (80-42-154-234.dynamic.dsl.as9105.com)

20150613205952: :cadance.canternet.org 433 * sleumasBot :Nickname is already in use.

20150613205954: PING :ycn}XmisnT
:cadance.canternet.org NOTICE sleumasBot_ :*** If you are having problems connecting due to ping timeouts, please type /quote PONG ycn}XmisnT or /raw PONG ycn}XmisnT now.

20150613205954: Ping Request Responded to Successfully
20150613205954: :cadance.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150613205954: :cadance.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150613205954: :cadance.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150613205955: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :sleumasBot_!sleumasBot@Pony-2kepf7.dsl.as9105.com has just authenticated as you (sleumas2000)
20150613205955: Link Closed. Reason: :NickServ!NickServ@canternet.org killed connection because :cadance.canternet.org!canternet.org!NickServ (Killed (NickServ (GHOST command used by sleumasBot_)))
20150613205955: :cadance.canternet.org NOTICE Auth :Welcome to Canternet!
:cadance.canternet.org 001 sleumasBot_ :Welcome to the Canternet IRC Network sleumasBot_!sleumasBot@80-42-154-234.dynamic.dsl.as9105.com
:cadance.canternet.org 002 sleumasBot_ :Your host is cadance.canternet.org, running version InspIRCd-2.0
:cadance.canternet.org 003 sleumasBot_ :This server was created 01:24:01 May 12 2015
:cadance.canternet.org 004 sleumasBot_ cadance.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:cadance.canternet.org 005 sleumasBot_ AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:cadance.canternet.org 005 sleumasBot_ KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150613205955: Ping Request Responded to Successfully
20150613205955: 
:cadance.canternet.org 005 sleumasBot_ SSL=0.0.0.0:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:cadance.canternet.org 042 sleumasBot_ 142ABWK4B :your unique ID
:cadance.canternet.org 375 sleumasBot_ :cadance.canternet.org message of the day
:cadance.canternet.org 372 sleumasBot_ :-                                                 Y
:cadance.canternet.org 372 sleumasBot_ :-                                                Yj
:cadance.canternet.org 372 sleumasBot_ :-                                              jYY
:cadance.canternet.org 372 sleumasBot_ :-                                      #YYTYYYYYYaT   B
:cadance.canternet.org 372 sleumasBot_ :-                                   zzFYYYYY        J#a
:cadance.canternet.org 372 sleumasBot_ :-                                 JDsJaF     EEBBHE6YYJ Y
:cadance.canternet.org 372 sleumasBot_ :-                                TDTTJTJ  EHFFGFGFGFFBE  Yz
:cadance.canternet.org 372 sleumasBot_ :-                               7 GTGTJTLEHBFGGRGGFFFGFFE
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :-                               Y RTnJTJTTYYEEFFGB  HFGFFBE
:cadance.canternet.org 372 sleumasBot_ :-                              x  RYTTJTJTHTTYY BFLYY EHBFBE
:cadance.canternet.org 372 sleumasBot_ :-                              1 EHYYTTJTsa    GE ZYPEE  EHEE
:cadance.canternet.org 372 sleumasBot_ :-                              s HBFYYJTas    EEEEYYJ E    EE
:cadance.canternet.org 372 sleumasBot_ :-                              1 EFFBYTTJx   zY  E TJ E
:cadance.canternet.org 372 sleumasBot_ :-        7jYTYTYYYT1            Y HFFTYYJa   1  EEYT@ E
:cadance.canternet.org 372 sleumasBot_ :-      nYYYYYYY     YT          z  HFFHYYJ#   aY EYTT E
:cadance.canternet.org 372 sleumasBot_ :-    1TYYYYYY  YEEE   YY         Y YBFBHET#Y   GDsTTJTRG
:cadance.canternet.org 372 sleumasBot_ :-   7YYYYYY  EBFFFFBBE  YJ       7Y FFGFYTJz#x YTJTJTeTB
:cadance.canternet.org 372 sleumasBot_ :-   TYYYYYY EFGRRRFFFFHE  x       x  HFFYYTTaa#asJJJFJB
:cadance.canternet.org 372 sleumasBot_ :-  nYYYYYY 1FGDRGFBHHEBHE  5FBFY   T  FFFYTTFis1zxLB
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :-  1YYYYYY EFDRGBE     EEDJJJTaa#F J  BFEYTTF
:cadance.canternet.org 372 sleumasBot_ :-  TYYYYYY EGRRFJ       GT JTJTaJsaJ  BBYTTJ8
:cadance.canternet.org 372 sleumasBot_ :-  YYYYYYY EFDGB        sTTTaJJJaTa  EBEYTJTL
:cadance.canternet.org 372 sleumasBot_ :-  7YYYYYY 0FRRB       FsYYsJaTJTJT EBBYTJJa8
:cadance.canternet.org 372 sleumasBot_ :-  7YYYYYY  BGGFE      DJTTJJTJTTT EHEYTJTaJB
:cadance.canternet.org 372 sleumasBot_ :-   YYYYYYY EFRFB       # JsTJTTJEEYYYYTJaJs
:cadance.canternet.org 372 sleumasBot_ :-   jYYYYYY  FGRFL      0aaJJTRTTTTTTTJTaJzG
:cadance.canternet.org 372 sleumasBot_ :-    7YYYYYY EFGFE      P#JJT1TTTTTJTJTTJX
:cadance.canternet.org 372 sleumasBot_ :-     jYYYYY  BGGF@      JJTTeneGTJJJTTRK
:cadance.canternet.org 372 sleumasBot_ :-      jYYYYY EFRFE    jsaTTD71 GTTJTX7nO
:cadance.canternet.org 372 sleumasBot_ :-       1YYYY  FGGB   BaaTJT7xG JJaJTnj7O
:cadance.canternet.org 372 sleumasBot_ :-       xYYYYY BRGFE  aaTJTR1jRYJJTJTp1jjZ
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :-       TYYYY  BGDFH GJJaTTLj7 GJTaTTi1zjF
:cadance.canternet.org 372 sleumasBot_ :-       xYYYY  BRRFH FTJJJTn1X FTJTTTRzxxF
:cadance.canternet.org 372 sleumasBot_ :-  #TTTYYYY   EGGRBE 1JTaJs7j@ iJTJTT8x#7P
:cadance.canternet.org 372 sleumasBot_ :-   1YYYYY   EFGGBH  #JJTJTn1e eTJJJTRz1zjR
:cadance.canternet.org 372 sleumasBot_ :-     7sJYYEHFFFBE   ssJJTT571pPTTJTTT71nnF
:cadance.canternet.org 372 sleumasBot_ :-       EEEEEEHE     zJJTJTR1eRGTJTaTTRXX@G 
:cadance.canternet.org 372 sleumasBot_ :-                    ZJTJTTR8  GJTJJJTG
:cadance.canternet.org 372 sleumasBot_ :-                    FGTTJTF    KJTaTJTi
:cadance.canternet.org 372 sleumasBot_ :- 
:cadance.canternet.org 372 sleumasBot_ :- /---------------------------------------------------------\
:cadance.canternet.org 372 sleumasBot_ :- |           Welcome to canternet.org IRC!                 |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :- | Rules: 1) No spamming/flooding                          |
:cadance.canternet.org 372 sleumasBot_ :- |        2) No abusive bots                               |
:cadance.canternet.org 372 sleumasBot_ :- | For more detailed rules, use the /rules command         |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
:cadance.canternet.org 372 sleumasBot_ :- | Ports:                                                  |
:cadance.canternet.org 372 sleumasBot_ :- |       SSL: 6660-6665                                    |
:cadance.canternet.org 372 sleumasBot_ :- |       non-SSL: 6666-6669                                |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
:cadance.canternet.org 372 sleumasBot_ :- | Official Channels:                                      |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :- |       Lobby: #Canternet                                 |
:cadance.canternet.org 372 sleumasBot_ :- |       Help:  #Help                                      |
:cadance.canternet.org 372 sleumasBot_ :- | For other channels use /list or /msg ALIS list          |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
:cadance.canternet.org 372 sleumasBot_ :- | Services:                                               |
:cadance.canternet.org 372 sleumasBot_ :- |    /msg NickServ help                                   |
:cadance.canternet.org 372 sleumasBot_ :- |    /msg ChanServ help                                   |
:cadance.canternet.org 372 sleumasBot_ :- |    /msg MemoServ help                                   |
:cadance.canternet.org 372 sleumasBot_ :- | For all other services: /msg HelpServ services          |
:cadance.canternet.org 372 sleumasBot_ :- |                                                         |
20150613205956: 
:cadance.canternet.org 372 sleumasBot_ :- \---------------------------------------------------------/
:cadance.canternet.org 376 sleumasBot_ :End of message of the day.
:cadance.canternet.org 251 sleumasBot_ :There are 7 users and 1116 invisible on 7 servers
:cadance.canternet.org 252 sleumasBot_ 40 :operator(s) online
:cadance.canternet.org 253 sleumasBot_ 1 :unknown connections
:cadance.canternet.org 254 sleumasBot_ 796 :channels formed
:cadance.canternet.org 255 sleumasBot_ :I have 489 clients and 2 servers
:cadance.canternet.org 265 sleumasBot_ :Current Local Users: 489  Max: 1009
:cadance.canternet.org 266 sleumasBot_ :Current Global Users: 1123  Max: 2151
:cadance.canternet.org 396 sleumasBot_ Pony-2kepf7.dsl.as9105.com :is now your displayed host
:sleumasBot_!sleumasBot@Pony-2kepf7.dsl.as9105.com MODE sleumasBot_ +xi
:cadance.canternet.org NOTICE sleumasBot_ :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:cadance.canternet.org NOTICE sleumasBot_ :*** Forwarding PASS to NickServ
20150613205956: 

20150613205956: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** End of Message(s) of the Day ***
20150613205957: 

20150613205957: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :Welcome to Canternet, sleumasBot_! Here on Canternet, we provide services to enable the registration of nicknames and channels! For details, type /msg NickServ help and /msg ChanServ help.
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot_ is not a registered nickname.

20150613205957: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :You are now identified for sleumas2000.
:cadance.canternet.org 900 sleumasBot_ sleumasBot_!sleumasBot@Pony-2kepf7.dsl.as9105.com sleumas2000 :You are now logged in as sleumas2000
:cadance.canternet.org MODE sleumasBot_ -x
:cadance.canternet.org 396 sleumasBot_ my.little.karaoke :is now your displayed host
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot has been ghosted.

20150613205957: :sleumasBot_!sleumasBot@my.little.karaoke NICK sleumasBot

20150613210000: Connected
20150613210000: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :You are already logged in as sleumas2000.
20150613210001: input: :sleumasBot!sleumasBot@my.little.karaoke JOIN :#Sleu
20150613210001: input: :cadance.canternet.org 332 sleumasBot #Sleu :#Sleu: The awesome Channel
20150613210001: input: :cadance.canternet.org 333 sleumasBot #Sleu sleumas2000 1422522563
20150613210001: input: :cadance.canternet.org 353 sleumasBot = #Sleu :hoofy RedHelper sleumasBot ~sleumas2000 
20150613210001: input: :cadance.canternet.org 366 sleumasBot #Sleu :End of /NAMES list.
20150613210002: input: :ChanServ!ChanServ@canternet.org MODE #Sleu +qo sleumasBot sleumasBot
20150613210002: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :What's DofE?
20150613210012: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :Duke of Ediburgh awards
20150613210026: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :it's a thing where you do community service and stuff, then go on a hike and you get a certificate
20150613210030: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :Universities like it
20150613210031: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :http://www.dofe.org/en/content/cms/doing-your-dofe/whats-the-dofe/
20150613210036: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :^ that
20150613210106: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :*so tired*
20150613210113: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :Well thats cool.
20150613210201: input: PING :cadance.canternet.org
20150613210201: input: PING :cadance.canternet.org
20150613210201: Ping Request Responded to Successfully
20150613210201: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613210201: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613210237: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :I know there is going some Spoilers for the 100th episode.
20150613210313: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :where?
20150613210324: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu :I still haven't seen 99.....
20150613210326: input: :sleumas2000!sleumie@my.little.karaoke PRIVMSG #Sleu ::P
20150613210332: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :Anywhrre on Canternet.
20150613210335: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :where*
20150613210346: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :of course I won't know what they will be talking about since I'm still on S1.
20150613210403: input: PING :cadance.canternet.org
20150613210403: input: PING :cadance.canternet.org
20150613210403: Ping Request Responded to Successfully
20150613210403: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613210403: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613210456: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :And someday when I get to the UK hoofy is going to help catch up on the seasons.
20150613210526: input: :hoofy!WebChat@Pony-7h5o2a.res.rr.com PRIVMSG #Sleu :yup
20150613210603: input: PING :cadance.canternet.org
20150613210603: input: PING :cadance.canternet.org
20150613210603: Ping Request Responded to Successfully
20150613210603: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613210603: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613210603: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :But maybe a while since I have a lot of money I gotta save up,
20150613210804: input: PING :cadance.canternet.org
20150613210804: input: PING :cadance.canternet.org
20150613210804: Ping Request Responded to Successfully
20150613210804: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613210804: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613211006: input: PING :cadance.canternet.org
20150613211006: input: PING :cadance.canternet.org
20150613211006: Ping Request Responded to Successfully
20150613211006: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613211006: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613211206: input: PING :cadance.canternet.org
20150613211206: input: PING :cadance.canternet.org
20150613211206: Ping Request Responded to Successfully
20150613211206: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613211206: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613211407: input: PING :cadance.canternet.org
20150613211407: input: PING :cadance.canternet.org
20150613211407: Ping Request Responded to Successfully
20150613211407: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613211407: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613211608: input: PING :cadance.canternet.org
20150613211608: input: PING :cadance.canternet.org
20150613211608: Ping Request Responded to Successfully
20150613211608: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613211608: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613211809: input: PING :cadance.canternet.org
20150613211809: input: PING :cadance.canternet.org
20150613211809: Ping Request Responded to Successfully
20150613211809: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613211809: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613212010: input: PING :cadance.canternet.org
20150613212010: input: PING :cadance.canternet.org
20150613212010: Ping Request Responded to Successfully
20150613212010: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613212010: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613212211: input: PING :cadance.canternet.org
20150613212211: input: PING :cadance.canternet.org
20150613212211: Ping Request Responded to Successfully
20150613212211: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613212211: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613212412: input: PING :cadance.canternet.org
20150613212412: input: PING :cadance.canternet.org
20150613212412: Ping Request Responded to Successfully
20150613212412: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613212412: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613212613: input: PING :cadance.canternet.org
20150613212613: input: PING :cadance.canternet.org
20150613212613: Ping Request Responded to Successfully
20150613212613: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613212613: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613212814: input: PING :cadance.canternet.org
20150613212814: input: PING :cadance.canternet.org
20150613212814: Ping Request Responded to Successfully
20150613212814: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613212814: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613213015: input: PING :cadance.canternet.org
20150613213015: input: PING :cadance.canternet.org
20150613213015: Ping Request Responded to Successfully
20150613213015: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613213015: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613213216: input: PING :cadance.canternet.org
20150613213216: input: PING :cadance.canternet.org
20150613213216: Ping Request Responded to Successfully
20150613213216: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613213216: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613213417: input: PING :cadance.canternet.org
20150613213417: input: PING :cadance.canternet.org
20150613213417: Ping Request Responded to Successfully
20150613213417: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613213417: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613213618: input: PING :cadance.canternet.org
20150613213618: input: PING :cadance.canternet.org
20150613213618: Ping Request Responded to Successfully
20150613213618: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613213618: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613213820: input: PING :cadance.canternet.org
20150613213820: input: PING :cadance.canternet.org
20150613213820: Ping Request Responded to Successfully
20150613213820: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613213820: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613214021: input: PING :cadance.canternet.org
20150613214021: input: PING :cadance.canternet.org
20150613214021: Ping Request Responded to Successfully
20150613214021: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613214021: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613214139: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :brb gotta make a call.
20150613214222: input: PING :cadance.canternet.org
20150613214222: input: PING :cadance.canternet.org
20150613214222: Ping Request Responded to Successfully
20150613214222: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613214222: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613214423: input: PING :cadance.canternet.org
20150613214423: input: PING :cadance.canternet.org
20150613214423: Ping Request Responded to Successfully
20150613214423: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613214423: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613214624: input: PING :cadance.canternet.org
20150613214624: input: PING :cadance.canternet.org
20150613214624: Ping Request Responded to Successfully
20150613214624: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613214624: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613214825: input: PING :cadance.canternet.org
20150613214825: input: PING :cadance.canternet.org
20150613214825: Ping Request Responded to Successfully
20150613214825: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613214825: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613215026: input: PING :cadance.canternet.org
20150613215026: input: PING :cadance.canternet.org
20150613215026: Ping Request Responded to Successfully
20150613215026: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613215026: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613215227: input: PING :cadance.canternet.org
20150613215227: input: PING :cadance.canternet.org
20150613215227: Ping Request Responded to Successfully
20150613215227: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613215227: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613215428: input: PING :cadance.canternet.org
20150613215428: input: PING :cadance.canternet.org
20150613215428: Ping Request Responded to Successfully
20150613215428: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613215428: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613215526: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :back
20150613215544: input: :hoofy!WebChat@Pony-7h5o2a.res.rr.com PRIVMSG #Sleu :hey
20150613215549: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :No one is answering. I'll back in like 10 minutes.
20150613215554: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :call back*
20150613215629: input: PING :cadance.canternet.org
20150613215629: input: PING :cadance.canternet.org
20150613215629: Ping Request Responded to Successfully
20150613215629: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613215629: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613215830: input: PING :cadance.canternet.org
20150613215830: input: PING :cadance.canternet.org
20150613215830: Ping Request Responded to Successfully
20150613215830: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613215830: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613220031: input: PING :cadance.canternet.org
20150613220031: input: PING :cadance.canternet.org
20150613220031: Ping Request Responded to Successfully
20150613220031: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613220031: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613220232: input: PING :cadance.canternet.org
20150613220234: input: PING :cadance.canternet.org
20150613220234: Ping Request Responded to Successfully
20150613220235: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613220235: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613220435: input: PING :cadance.canternet.org
20150613220442: input: PING :cadance.canternet.org
20150613220442: Ping Request Responded to Successfully
20150613220443: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613220443: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613220643: input: PING :cadance.canternet.org
20150613220643: input: PING :cadance.canternet.org
20150613220643: Ping Request Responded to Successfully
20150613220643: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613220643: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613220844: input: PING :cadance.canternet.org
20150613220845: input: PING :cadance.canternet.org
20150613220845: Ping Request Responded to Successfully
20150613220845: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613220845: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613221046: input: PING :cadance.canternet.org
20150613221046: input: PING :cadance.canternet.org
20150613221046: Ping Request Responded to Successfully
20150613221046: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613221046: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613221247: input: PING :cadance.canternet.org
20150613221247: input: PING :cadance.canternet.org
20150613221247: Ping Request Responded to Successfully
20150613221247: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613221247: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613221448: input: PING :cadance.canternet.org
20150613221450: input: PING :cadance.canternet.org
20150613221450: Ping Request Responded to Successfully
20150613221452: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613221452: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613221651: input: PING :cadance.canternet.org
20150613221651: input: PING :cadance.canternet.org
20150613221651: Ping Request Responded to Successfully
20150613221651: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613221651: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613221852: input: PING :cadance.canternet.org
20150613221852: input: PING :cadance.canternet.org
20150613221852: Ping Request Responded to Successfully
20150613221852: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613221852: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613222053: input: PING :cadance.canternet.org
20150613222053: input: PING :cadance.canternet.org
20150613222053: Ping Request Responded to Successfully
20150613222053: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613222053: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613222209: input: :SaslServ!SaslServ@canternet.org NOTICE sleumasBot :sleumasPhone!uid91753@Pony-pu5auv.charlton.irccloud.com has just authenticated as you (sleumas2000)
20150613222210: input: :sleumasPhone!uid91753@my.little.karaoke JOIN :#Sleu
20150613222211: input: :ChanServ!ChanServ@canternet.org MODE #Sleu +qo sleumasPhone sleumasPhone
20150613222254: input: PING :cadance.canternet.org
20150613222254: input: PING :cadance.canternet.org
20150613222254: Ping Request Responded to Successfully
20150613222254: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613222254: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613222455: input: PING :cadance.canternet.org
20150613222455: input: PING :cadance.canternet.org
20150613222455: Ping Request Responded to Successfully
20150613222455: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613222455: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613222656: input: PING :cadance.canternet.org
20150613222656: input: PING :cadance.canternet.org
20150613222656: Ping Request Responded to Successfully
20150613222656: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613222656: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613222857: input: PING :cadance.canternet.org
20150613222857: input: PING :cadance.canternet.org
20150613222857: Ping Request Responded to Successfully
20150613222857: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613222857: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613223058: input: PING :cadance.canternet.org
20150613223058: input: PING :cadance.canternet.org
20150613223058: Ping Request Responded to Successfully
20150613223058: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613223058: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613223259: input: PING :cadance.canternet.org
20150613223259: input: PING :cadance.canternet.org
20150613223259: Ping Request Responded to Successfully
20150613223259: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613223259: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613223500: input: PING :cadance.canternet.org
20150613223500: input: PING :cadance.canternet.org
20150613223500: Ping Request Responded to Successfully
20150613223500: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613223500: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613223701: input: PING :cadance.canternet.org
20150613223701: input: PING :cadance.canternet.org
20150613223701: Ping Request Responded to Successfully
20150613223701: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613223701: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613223902: input: PING :cadance.canternet.org
20150613223902: input: PING :cadance.canternet.org
20150613223902: Ping Request Responded to Successfully
20150613223902: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613223902: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613224103: input: PING :cadance.canternet.org
20150613224103: input: PING :cadance.canternet.org
20150613224103: Ping Request Responded to Successfully
20150613224103: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613224103: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613224304: input: PING :cadance.canternet.org
20150613224304: input: PING :cadance.canternet.org
20150613224304: Ping Request Responded to Successfully
20150613224304: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613224304: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613224505: input: PING :cadance.canternet.org
20150613224505: input: PING :cadance.canternet.org
20150613224505: Ping Request Responded to Successfully
20150613224505: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613224505: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613224706: input: PING :cadance.canternet.org
20150613224706: input: PING :cadance.canternet.org
20150613224706: Ping Request Responded to Successfully
20150613224706: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613224706: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613224907: input: PING :cadance.canternet.org
20150613224907: input: PING :cadance.canternet.org
20150613224907: Ping Request Responded to Successfully
20150613224907: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613224907: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613225108: input: PING :cadance.canternet.org
20150613225108: input: PING :cadance.canternet.org
20150613225108: Ping Request Responded to Successfully
20150613225108: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613225108: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613225309: input: PING :cadance.canternet.org
20150613225309: input: PING :cadance.canternet.org
20150613225309: Ping Request Responded to Successfully
20150613225309: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613225309: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613225510: input: PING :cadance.canternet.org
20150613225510: input: PING :cadance.canternet.org
20150613225510: Ping Request Responded to Successfully
20150613225510: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613225510: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613225711: input: PING :cadance.canternet.org
20150613225711: input: PING :cadance.canternet.org
20150613225711: Ping Request Responded to Successfully
20150613225711: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613225711: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613225912: input: PING :cadance.canternet.org
20150613225912: input: PING :cadance.canternet.org
20150613225912: Ping Request Responded to Successfully
20150613225912: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613225912: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613230113: input: PING :cadance.canternet.org
20150613230113: input: PING :cadance.canternet.org
20150613230113: Ping Request Responded to Successfully
20150613230113: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613230113: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613230314: input: PING :cadance.canternet.org
20150613230314: input: PING :cadance.canternet.org
20150613230314: Ping Request Responded to Successfully
20150613230314: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613230314: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613230515: input: PING :cadance.canternet.org
20150613230515: input: PING :cadance.canternet.org
20150613230515: Ping Request Responded to Successfully
20150613230515: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613230515: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613230716: input: PING :cadance.canternet.org
20150613230716: input: PING :cadance.canternet.org
20150613230716: Ping Request Responded to Successfully
20150613230716: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613230716: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613230917: input: PING :cadance.canternet.org
20150613230917: input: PING :cadance.canternet.org
20150613230917: Ping Request Responded to Successfully
20150613230917: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613230917: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613231118: input: PING :cadance.canternet.org
20150613231118: input: PING :cadance.canternet.org
20150613231118: Ping Request Responded to Successfully
20150613231118: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613231118: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613231319: input: PING :cadance.canternet.org
20150613231319: input: PING :cadance.canternet.org
20150613231319: Ping Request Responded to Successfully
20150613231319: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613231319: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613231520: input: PING :cadance.canternet.org
20150613231520: input: PING :cadance.canternet.org
20150613231520: Ping Request Responded to Successfully
20150613231520: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613231520: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613231721: input: PING :cadance.canternet.org
20150613231721: input: PING :cadance.canternet.org
20150613231721: Ping Request Responded to Successfully
20150613231721: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613231721: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613231922: input: PING :cadance.canternet.org
20150613231922: input: PING :cadance.canternet.org
20150613231922: Ping Request Responded to Successfully
20150613231922: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613231922: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613232123: input: PING :cadance.canternet.org
20150613232123: input: PING :cadance.canternet.org
20150613232123: Ping Request Responded to Successfully
20150613232123: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613232123: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613232324: input: PING :cadance.canternet.org
20150613232324: input: PING :cadance.canternet.org
20150613232324: Ping Request Responded to Successfully
20150613232324: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613232324: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613232525: input: PING :cadance.canternet.org
20150613232525: input: PING :cadance.canternet.org
20150613232525: Ping Request Responded to Successfully
20150613232525: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613232525: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613232726: input: PING :cadance.canternet.org
20150613232726: input: PING :cadance.canternet.org
20150613232726: Ping Request Responded to Successfully
20150613232726: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613232726: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613232927: input: PING :cadance.canternet.org
20150613232927: input: PING :cadance.canternet.org
20150613232927: Ping Request Responded to Successfully
20150613232927: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613232927: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613233128: input: PING :cadance.canternet.org
20150613233128: input: PING :cadance.canternet.org
20150613233128: Ping Request Responded to Successfully
20150613233128: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613233128: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613233329: input: PING :cadance.canternet.org
20150613233329: input: PING :cadance.canternet.org
20150613233329: Ping Request Responded to Successfully
20150613233329: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613233329: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613233530: input: PING :cadance.canternet.org
20150613233530: input: PING :cadance.canternet.org
20150613233530: Ping Request Responded to Successfully
20150613233530: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613233530: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613233731: input: PING :cadance.canternet.org
20150613233731: input: PING :cadance.canternet.org
20150613233731: Ping Request Responded to Successfully
20150613233731: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613233731: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613233932: input: PING :cadance.canternet.org
20150613233932: input: PING :cadance.canternet.org
20150613233932: Ping Request Responded to Successfully
20150613233932: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613233932: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613234133: input: PING :cadance.canternet.org
20150613234133: input: PING :cadance.canternet.org
20150613234133: Ping Request Responded to Successfully
20150613234133: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613234133: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613234334: input: PING :cadance.canternet.org
20150613234334: input: PING :cadance.canternet.org
20150613234334: Ping Request Responded to Successfully
20150613234334: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613234334: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613234535: input: PING :cadance.canternet.org
20150613234535: input: PING :cadance.canternet.org
20150613234535: Ping Request Responded to Successfully
20150613234535: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613234535: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613234736: input: PING :cadance.canternet.org
20150613234736: input: PING :cadance.canternet.org
20150613234736: Ping Request Responded to Successfully
20150613234736: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613234736: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613234937: input: PING :cadance.canternet.org
20150613234937: input: PING :cadance.canternet.org
20150613234937: Ping Request Responded to Successfully
20150613234937: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613234937: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613235138: input: PING :cadance.canternet.org
20150613235138: input: PING :cadance.canternet.org
20150613235138: Ping Request Responded to Successfully
20150613235138: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613235138: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613235339: input: PING :cadance.canternet.org
20150613235339: input: PING :cadance.canternet.org
20150613235339: Ping Request Responded to Successfully
20150613235339: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613235339: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613235540: input: PING :cadance.canternet.org
20150613235540: input: PING :cadance.canternet.org
20150613235540: Ping Request Responded to Successfully
20150613235540: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613235540: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613235741: input: PING :cadance.canternet.org
20150613235741: input: PING :cadance.canternet.org
20150613235741: Ping Request Responded to Successfully
20150613235741: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613235741: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150613235942: input: PING :cadance.canternet.org
20150613235942: input: PING :cadance.canternet.org
20150613235942: Ping Request Responded to Successfully
20150613235942: Exception in main loop: 'NoneType' object has no attribute 'values'
20150613235942: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614000146: input: PING :cadance.canternet.org
20150614000146: input: PING :cadance.canternet.org
20150614000146: Ping Request Responded to Successfully
20150614000146: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614000146: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614000347: input: PING :cadance.canternet.org
20150614000347: input: PING :cadance.canternet.org
20150614000347: Ping Request Responded to Successfully
20150614000347: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614000347: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614000548: input: PING :cadance.canternet.org
20150614000548: input: PING :cadance.canternet.org
20150614000548: Ping Request Responded to Successfully
20150614000548: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614000548: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614000749: input: PING :cadance.canternet.org
20150614000749: input: PING :cadance.canternet.org
20150614000749: Ping Request Responded to Successfully
20150614000749: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614000749: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614000950: input: PING :cadance.canternet.org
20150614000950: input: PING :cadance.canternet.org
20150614000950: Ping Request Responded to Successfully
20150614000950: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614000950: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614001151: input: PING :cadance.canternet.org
20150614001151: input: PING :cadance.canternet.org
20150614001151: Ping Request Responded to Successfully
20150614001151: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614001151: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614001352: input: PING :cadance.canternet.org
20150614001352: input: PING :cadance.canternet.org
20150614001352: Ping Request Responded to Successfully
20150614001352: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614001352: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614001553: input: PING :cadance.canternet.org
20150614001553: input: PING :cadance.canternet.org
20150614001553: Ping Request Responded to Successfully
20150614001553: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614001553: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614001754: input: PING :cadance.canternet.org
20150614001754: input: PING :cadance.canternet.org
20150614001754: Ping Request Responded to Successfully
20150614001754: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614001754: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614001955: input: PING :cadance.canternet.org
20150614001955: input: PING :cadance.canternet.org
20150614001955: Ping Request Responded to Successfully
20150614001955: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614001955: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614002156: input: PING :cadance.canternet.org
20150614002156: input: PING :cadance.canternet.org
20150614002156: Ping Request Responded to Successfully
20150614002156: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614002156: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614002357: input: PING :cadance.canternet.org
20150614002357: input: PING :cadance.canternet.org
20150614002357: Ping Request Responded to Successfully
20150614002357: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614002357: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614002558: input: PING :cadance.canternet.org
20150614002558: input: PING :cadance.canternet.org
20150614002558: Ping Request Responded to Successfully
20150614002558: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614002558: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614002759: input: PING :cadance.canternet.org
20150614002759: input: PING :cadance.canternet.org
20150614002759: Ping Request Responded to Successfully
20150614002759: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614002759: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614003000: input: PING :cadance.canternet.org
20150614003000: input: PING :cadance.canternet.org
20150614003000: Ping Request Responded to Successfully
20150614003000: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614003000: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614003201: input: PING :cadance.canternet.org
20150614003201: input: PING :cadance.canternet.org
20150614003201: Ping Request Responded to Successfully
20150614003201: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614003201: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614003402: input: PING :cadance.canternet.org
20150614003402: input: PING :cadance.canternet.org
20150614003402: Ping Request Responded to Successfully
20150614003402: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614003402: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614003603: input: PING :cadance.canternet.org
20150614003604: input: PING :cadance.canternet.org
20150614003604: Ping Request Responded to Successfully
20150614003605: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614003605: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614003805: input: PING :cadance.canternet.org
20150614003805: input: PING :cadance.canternet.org
20150614003805: Ping Request Responded to Successfully
20150614003805: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614003806: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614004006: input: PING :cadance.canternet.org
20150614004006: input: PING :cadance.canternet.org
20150614004006: Ping Request Responded to Successfully
20150614004006: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614004006: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614004207: input: PING :cadance.canternet.org
20150614004207: input: PING :cadance.canternet.org
20150614004207: Ping Request Responded to Successfully
20150614004207: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614004207: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614004408: input: PING :cadance.canternet.org
20150614004408: input: PING :cadance.canternet.org
20150614004408: Ping Request Responded to Successfully
20150614004408: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614004408: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614004609: input: PING :cadance.canternet.org
20150614004609: input: PING :cadance.canternet.org
20150614004609: Ping Request Responded to Successfully
20150614004609: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614004609: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614004810: input: PING :cadance.canternet.org
20150614004810: input: PING :cadance.canternet.org
20150614004810: Ping Request Responded to Successfully
20150614004810: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614004810: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614005011: input: PING :cadance.canternet.org
20150614005011: input: PING :cadance.canternet.org
20150614005011: Ping Request Responded to Successfully
20150614005011: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614005011: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614005212: input: PING :cadance.canternet.org
20150614005212: input: PING :cadance.canternet.org
20150614005212: Ping Request Responded to Successfully
20150614005212: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614005212: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614005413: input: PING :cadance.canternet.org
20150614005413: input: PING :cadance.canternet.org
20150614005413: Ping Request Responded to Successfully
20150614005413: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614005413: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614005614: input: PING :cadance.canternet.org
20150614005614: input: PING :cadance.canternet.org
20150614005614: Ping Request Responded to Successfully
20150614005614: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614005614: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614005815: input: PING :cadance.canternet.org
20150614005815: input: PING :cadance.canternet.org
20150614005815: Ping Request Responded to Successfully
20150614005815: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614005815: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614010016: input: PING :cadance.canternet.org
20150614010016: input: PING :cadance.canternet.org
20150614010016: Ping Request Responded to Successfully
20150614010016: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614010016: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614010216: input: PING :cadance.canternet.org
20150614010217: input: PING :cadance.canternet.org
20150614010217: Ping Request Responded to Successfully
20150614010217: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614010217: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614010312: input: :sleumasPhone!uid91753@my.little.karaoke QUIT :Quit: Connection closed for inactivity
20150614010418: input: PING :cadance.canternet.org
20150614010422: input: PING :cadance.canternet.org
20150614010422: Ping Request Responded to Successfully
20150614010423: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614010423: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614010622: input: PING :cadance.canternet.org
20150614010625: input: PING :cadance.canternet.org
20150614010625: Ping Request Responded to Successfully
20150614010625: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614010625: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614010826: input: PING :cadance.canternet.org
20150614010826: input: PING :cadance.canternet.org
20150614010826: Ping Request Responded to Successfully
20150614010826: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614010826: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614011027: input: PING :cadance.canternet.org
20150614011027: input: PING :cadance.canternet.org
20150614011027: Ping Request Responded to Successfully
20150614011027: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614011027: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614011227: input: PING :cadance.canternet.org
20150614011228: input: PING :cadance.canternet.org
20150614011228: Ping Request Responded to Successfully
20150614011228: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614011228: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614011429: input: PING :cadance.canternet.org
20150614011429: input: PING :cadance.canternet.org
20150614011429: Ping Request Responded to Successfully
20150614011429: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614011429: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614011610: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile NICK RedHelper[NLR]
20150614011630: input: PING :cadance.canternet.org
20150614011630: input: PING :cadance.canternet.org
20150614011630: Ping Request Responded to Successfully
20150614011630: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614011630: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614011831: input: PING :cadance.canternet.org
20150614011831: input: PING :cadance.canternet.org
20150614011831: Ping Request Responded to Successfully
20150614011831: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614011831: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614012032: input: PING :cadance.canternet.org
20150614012032: input: PING :cadance.canternet.org
20150614012032: Ping Request Responded to Successfully
20150614012032: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614012032: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614012233: input: PING :cadance.canternet.org
20150614012233: input: PING :cadance.canternet.org
20150614012233: Ping Request Responded to Successfully
20150614012233: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614012233: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614012433: input: PING :cadance.canternet.org
20150614012433: input: PING :cadance.canternet.org
20150614012434: Ping Request Responded to Successfully
20150614012434: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614012434: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614012634: input: PING :cadance.canternet.org
20150614012634: input: PING :cadance.canternet.org
20150614012635: Ping Request Responded to Successfully
20150614012635: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614012635: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614012836: input: PING :cadance.canternet.org
20150614012836: input: PING :cadance.canternet.org
20150614012836: Ping Request Responded to Successfully
20150614012836: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614012836: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614013036: input: PING :cadance.canternet.org
20150614013037: input: PING :cadance.canternet.org
20150614013037: Ping Request Responded to Successfully
20150614013037: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614013037: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614013238: input: PING :cadance.canternet.org
20150614013238: input: PING :cadance.canternet.org
20150614013238: Ping Request Responded to Successfully
20150614013238: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614013238: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614013438: input: PING :cadance.canternet.org
20150614013438: input: PING :cadance.canternet.org
20150614013438: Ping Request Responded to Successfully
20150614013439: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614013439: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614013639: input: PING :cadance.canternet.org
20150614013639: input: PING :cadance.canternet.org
20150614013639: Ping Request Responded to Successfully
20150614013639: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614013640: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614013841: input: PING :cadance.canternet.org
20150614013841: input: PING :cadance.canternet.org
20150614013841: Ping Request Responded to Successfully
20150614013841: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614013841: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614014041: input: PING :cadance.canternet.org
20150614014041: input: PING :cadance.canternet.org
20150614014042: Ping Request Responded to Successfully
20150614014042: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614014042: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614014242: input: PING :cadance.canternet.org
20150614014242: input: PING :cadance.canternet.org
20150614014242: Ping Request Responded to Successfully
20150614014242: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614014242: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614014444: input: PING :cadance.canternet.org
20150614014444: input: PING :cadance.canternet.org
20150614014444: Ping Request Responded to Successfully
20150614014444: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614014444: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614014644: input: PING :cadance.canternet.org
20150614014644: input: PING :cadance.canternet.org
20150614014644: Ping Request Responded to Successfully
20150614014644: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614014644: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614014845: input: PING :cadance.canternet.org
20150614014845: input: PING :cadance.canternet.org
20150614014845: Ping Request Responded to Successfully
20150614014845: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614014845: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614015046: input: PING :cadance.canternet.org
20150614015046: input: PING :cadance.canternet.org
20150614015046: Ping Request Responded to Successfully
20150614015046: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614015047: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614015247: input: PING :cadance.canternet.org
20150614015247: input: PING :cadance.canternet.org
20150614015247: Ping Request Responded to Successfully
20150614015248: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614015248: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614015424: input: :RedHelper[NLR]!RedHelper@The.Pony.That.Makes.You.Smile NICK RedHelper
20150614015448: input: PING :cadance.canternet.org
20150614015448: input: PING :cadance.canternet.org
20150614015448: Ping Request Responded to Successfully
20150614015448: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614015448: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614015650: input: PING :cadance.canternet.org
20150614015650: input: PING :cadance.canternet.org
20150614015650: Ping Request Responded to Successfully
20150614015650: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614015650: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614015850: input: PING :cadance.canternet.org
20150614015850: input: PING :cadance.canternet.org
20150614015850: Ping Request Responded to Successfully
20150614015850: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614015851: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614020051: input: PING :cadance.canternet.org
20150614020051: input: PING :cadance.canternet.org
20150614020051: Ping Request Responded to Successfully
20150614020052: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614020052: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614020252: input: PING :cadance.canternet.org
20150614020252: input: PING :cadance.canternet.org
20150614020252: Ping Request Responded to Successfully
20150614020252: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614020252: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614020453: input: PING :cadance.canternet.org
20150614020453: input: PING :cadance.canternet.org
20150614020453: Ping Request Responded to Successfully
20150614020453: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614020453: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614020654: input: PING :cadance.canternet.org
20150614020654: input: PING :cadance.canternet.org
20150614020654: Ping Request Responded to Successfully
20150614020654: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614020655: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614020855: input: PING :cadance.canternet.org
20150614020855: input: PING :cadance.canternet.org
20150614020856: Ping Request Responded to Successfully
20150614020856: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614020856: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614021056: input: PING :cadance.canternet.org
20150614021056: input: PING :cadance.canternet.org
20150614021056: Ping Request Responded to Successfully
20150614021056: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614021056: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614021258: input: PING :cadance.canternet.org
20150614021258: input: PING :cadance.canternet.org
20150614021258: Ping Request Responded to Successfully
20150614021258: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614021258: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614021459: input: PING :cadance.canternet.org
20150614021459: input: PING :cadance.canternet.org
20150614021459: Ping Request Responded to Successfully
20150614021459: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614021459: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614021659: input: PING :cadance.canternet.org
20150614021659: input: PING :cadance.canternet.org
20150614021659: Ping Request Responded to Successfully
20150614021659: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614021659: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614021900: input: PING :cadance.canternet.org
20150614021900: input: PING :cadance.canternet.org
20150614021900: Ping Request Responded to Successfully
20150614021900: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614021900: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614022027: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :So hoofy
20150614022028: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :https://www.youtube.com/watch?v=5E7DERCMskk
20150614022043: input: :RedHelper!RedHelper@The.Pony.That.Makes.You.Smile PRIVMSG #Sleu :I am going to download the game and play it.
20150614022053: input: :hoofy!WebChat@Pony-7h5o2a.res.rr.com PRIVMSG #Sleu :ok
20150614022101: input: PING :cadance.canternet.org
20150614022101: input: PING :cadance.canternet.org
20150614022101: Ping Request Responded to Successfully
20150614022101: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614022101: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614022302: input: PING :cadance.canternet.org
20150614022302: input: PING :cadance.canternet.org
20150614022302: Ping Request Responded to Successfully
20150614022302: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614022302: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614022503: input: PING :cadance.canternet.org
20150614022503: input: PING :cadance.canternet.org
20150614022503: Ping Request Responded to Successfully
20150614022503: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614022503: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614022704: input: PING :cadance.canternet.org
20150614022704: input: PING :cadance.canternet.org
20150614022704: Ping Request Responded to Successfully
20150614022704: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614022704: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614022905: input: PING :cadance.canternet.org
20150614022905: input: PING :cadance.canternet.org
20150614022905: Ping Request Responded to Successfully
20150614022905: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614022905: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614023107: input: PING :cadance.canternet.org
20150614023107: input: PING :cadance.canternet.org
20150614023107: Ping Request Responded to Successfully
20150614023107: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614023107: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614023307: input: PING :cadance.canternet.org
20150614023307: input: PING :cadance.canternet.org
20150614023307: Ping Request Responded to Successfully
20150614023308: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614023308: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614023508: input: PING :cadance.canternet.org
20150614023508: input: PING :cadance.canternet.org
20150614023508: Ping Request Responded to Successfully
20150614023508: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614023508: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614023709: input: PING :cadance.canternet.org
20150614023709: input: PING :cadance.canternet.org
20150614023709: Ping Request Responded to Successfully
20150614023709: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614023710: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614023910: input: PING :cadance.canternet.org
20150614023910: input: PING :cadance.canternet.org
20150614023910: Ping Request Responded to Successfully
20150614023910: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614023910: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614024111: input: PING :cadance.canternet.org
20150614024112: input: PING :cadance.canternet.org
20150614024112: Ping Request Responded to Successfully
20150614024112: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614024112: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614024312: input: PING :cadance.canternet.org
20150614024312: input: PING :cadance.canternet.org
20150614024312: Ping Request Responded to Successfully
20150614024312: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614024312: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614024513: input: PING :cadance.canternet.org
20150614024513: input: PING :cadance.canternet.org
20150614024513: Ping Request Responded to Successfully
20150614024513: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614024513: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614024714: input: PING :cadance.canternet.org
20150614024714: input: PING :cadance.canternet.org
20150614024714: Ping Request Responded to Successfully
20150614024714: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614024714: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614024915: input: PING :cadance.canternet.org
20150614024915: input: PING :cadance.canternet.org
20150614024915: Ping Request Responded to Successfully
20150614024915: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614024915: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614025116: input: PING :cadance.canternet.org
20150614025116: input: PING :cadance.canternet.org
20150614025117: Ping Request Responded to Successfully
20150614025117: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614025117: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614025317: input: PING :cadance.canternet.org
20150614025317: input: PING :cadance.canternet.org
20150614025317: Ping Request Responded to Successfully
20150614025317: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614025317: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614025518: input: PING :cadance.canternet.org
20150614025518: input: PING :cadance.canternet.org
20150614025518: Ping Request Responded to Successfully
20150614025518: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614025518: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614025719: input: PING :cadance.canternet.org
20150614025719: input: PING :cadance.canternet.org
20150614025719: Ping Request Responded to Successfully
20150614025719: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614025719: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614025921: input: PING :cadance.canternet.org
20150614025921: input: PING :cadance.canternet.org
20150614025921: Ping Request Responded to Successfully
20150614025921: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614025921: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614030121: input: PING :cadance.canternet.org
20150614030121: input: PING :cadance.canternet.org
20150614030121: Ping Request Responded to Successfully
20150614030121: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614030121: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614030322: input: PING :cadance.canternet.org
20150614030322: input: PING :cadance.canternet.org
20150614030322: Ping Request Responded to Successfully
20150614030322: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614030322: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614030523: input: PING :cadance.canternet.org
20150614030523: input: PING :cadance.canternet.org
20150614030523: Ping Request Responded to Successfully
20150614030523: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614030523: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614030724: input: PING :cadance.canternet.org
20150614030724: input: PING :cadance.canternet.org
20150614030724: Ping Request Responded to Successfully
20150614030724: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614030724: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614030926: input: PING :cadance.canternet.org
20150614030926: input: PING :cadance.canternet.org
20150614030926: Ping Request Responded to Successfully
20150614030926: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614030926: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614031126: input: PING :cadance.canternet.org
20150614031126: input: PING :cadance.canternet.org
20150614031126: Ping Request Responded to Successfully
20150614031126: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614031126: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614031327: input: PING :cadance.canternet.org
20150614031327: input: PING :cadance.canternet.org
20150614031327: Ping Request Responded to Successfully
20150614031328: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614031328: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614031529: input: PING :cadance.canternet.org
20150614031529: input: PING :cadance.canternet.org
20150614031529: Ping Request Responded to Successfully
20150614031529: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614031529: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614031729: input: PING :cadance.canternet.org
20150614031729: input: PING :cadance.canternet.org
20150614031729: Ping Request Responded to Successfully
20150614031729: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614031729: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614031930: input: PING :cadance.canternet.org
20150614031930: input: PING :cadance.canternet.org
20150614031930: Ping Request Responded to Successfully
20150614031930: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614031930: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614032132: input: PING :cadance.canternet.org
20150614032132: input: PING :cadance.canternet.org
20150614032132: Ping Request Responded to Successfully
20150614032132: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614032132: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614032332: input: PING :cadance.canternet.org
20150614032332: input: PING :cadance.canternet.org
20150614032332: Ping Request Responded to Successfully
20150614032332: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614032332: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614032533: input: PING :cadance.canternet.org
20150614032533: input: PING :cadance.canternet.org
20150614032533: Ping Request Responded to Successfully
20150614032533: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614032533: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614032734: input: PING :cadance.canternet.org
20150614032734: input: PING :cadance.canternet.org
20150614032734: Ping Request Responded to Successfully
20150614032734: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614032734: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614032935: input: PING :cadance.canternet.org
20150614032935: input: PING :cadance.canternet.org
20150614032935: Ping Request Responded to Successfully
20150614032935: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614032935: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614033136: input: PING :cadance.canternet.org
20150614033136: input: PING :cadance.canternet.org
20150614033136: Ping Request Responded to Successfully
20150614033136: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614033136: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614033337: input: PING :cadance.canternet.org
20150614033337: input: PING :cadance.canternet.org
20150614033337: Ping Request Responded to Successfully
20150614033337: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614033337: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614033538: input: PING :cadance.canternet.org
20150614033538: input: PING :cadance.canternet.org
20150614033538: Ping Request Responded to Successfully
20150614033538: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614033538: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614033739: input: PING :cadance.canternet.org
20150614033739: input: PING :cadance.canternet.org
20150614033739: Ping Request Responded to Successfully
20150614033739: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614033739: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614033940: input: PING :cadance.canternet.org
20150614033940: input: PING :cadance.canternet.org
20150614033940: Ping Request Responded to Successfully
20150614033940: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614033940: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614034141: input: PING :cadance.canternet.org
20150614034141: input: PING :cadance.canternet.org
20150614034141: Ping Request Responded to Successfully
20150614034141: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614034141: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614034342: input: PING :cadance.canternet.org
20150614034342: input: PING :cadance.canternet.org
20150614034342: Ping Request Responded to Successfully
20150614034342: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614034342: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614034544: input: PING :cadance.canternet.org
20150614034544: input: PING :cadance.canternet.org
20150614034544: Ping Request Responded to Successfully
20150614034544: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614034544: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614034744: input: PING :cadance.canternet.org
20150614034744: input: PING :cadance.canternet.org
20150614034744: Ping Request Responded to Successfully
20150614034744: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614034744: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614034945: input: PING :cadance.canternet.org
20150614034945: input: PING :cadance.canternet.org
20150614034945: Ping Request Responded to Successfully
20150614034945: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614034945: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614035147: input: PING :cadance.canternet.org
20150614035147: input: PING :cadance.canternet.org
20150614035147: Ping Request Responded to Successfully
20150614035147: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614035147: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614035347: input: PING :cadance.canternet.org
20150614035347: input: PING :cadance.canternet.org
20150614035347: Ping Request Responded to Successfully
20150614035347: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614035347: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614035548: input: PING :cadance.canternet.org
20150614035548: input: PING :cadance.canternet.org
20150614035548: Ping Request Responded to Successfully
20150614035548: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614035548: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614035749: input: PING :cadance.canternet.org
20150614035749: input: PING :cadance.canternet.org
20150614035749: Ping Request Responded to Successfully
20150614035749: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614035749: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614035950: input: PING :cadance.canternet.org
20150614035950: input: PING :cadance.canternet.org
20150614035950: Ping Request Responded to Successfully
20150614035950: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614035950: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614040151: input: PING :cadance.canternet.org
20150614040151: input: PING :cadance.canternet.org
20150614040151: Ping Request Responded to Successfully
20150614040151: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614040151: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614040352: input: PING :cadance.canternet.org
20150614040352: input: PING :cadance.canternet.org
20150614040352: Ping Request Responded to Successfully
20150614040352: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614040352: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614040553: input: PING :cadance.canternet.org
20150614040553: input: PING :cadance.canternet.org
20150614040553: Ping Request Responded to Successfully
20150614040553: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614040554: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614040754: input: PING :cadance.canternet.org
20150614040754: input: PING :cadance.canternet.org
20150614040754: Ping Request Responded to Successfully
20150614040754: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614040754: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614040955: input: PING :cadance.canternet.org
20150614040956: input: PING :cadance.canternet.org
20150614040956: Ping Request Responded to Successfully
20150614040956: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614040956: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614041156: input: PING :cadance.canternet.org
20150614041156: input: PING :cadance.canternet.org
20150614041156: Ping Request Responded to Successfully
20150614041156: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614041156: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614041357: input: PING :cadance.canternet.org
20150614041357: input: PING :cadance.canternet.org
20150614041357: Ping Request Responded to Successfully
20150614041357: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614041357: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614041558: input: PING :cadance.canternet.org
20150614041558: input: PING :cadance.canternet.org
20150614041558: Ping Request Responded to Successfully
20150614041558: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614041558: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614041759: input: PING :cadance.canternet.org
20150614041759: input: PING :cadance.canternet.org
20150614041759: Ping Request Responded to Successfully
20150614041759: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614041759: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614042000: input: PING :cadance.canternet.org
20150614042000: input: PING :cadance.canternet.org
20150614042000: Ping Request Responded to Successfully
20150614042000: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614042000: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614042201: input: PING :cadance.canternet.org
20150614042201: input: PING :cadance.canternet.org
20150614042201: Ping Request Responded to Successfully
20150614042202: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614042202: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614042402: input: PING :cadance.canternet.org
20150614042402: input: PING :cadance.canternet.org
20150614042402: Ping Request Responded to Successfully
20150614042402: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614042402: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614042603: input: PING :cadance.canternet.org
20150614042603: input: PING :cadance.canternet.org
20150614042603: Ping Request Responded to Successfully
20150614042603: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614042604: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614042804: input: PING :cadance.canternet.org
20150614042804: input: PING :cadance.canternet.org
20150614042804: Ping Request Responded to Successfully
20150614042804: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614042804: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614043006: input: PING :cadance.canternet.org
20150614043006: input: PING :cadance.canternet.org
20150614043006: Ping Request Responded to Successfully
20150614043006: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614043006: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614043206: input: PING :cadance.canternet.org
20150614043206: input: PING :cadance.canternet.org
20150614043206: Ping Request Responded to Successfully
20150614043206: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614043206: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614043407: input: PING :cadance.canternet.org
20150614043407: input: PING :cadance.canternet.org
20150614043407: Ping Request Responded to Successfully
20150614043407: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614043407: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614043608: input: PING :cadance.canternet.org
20150614043608: input: PING :cadance.canternet.org
20150614043608: Ping Request Responded to Successfully
20150614043608: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614043608: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614043809: input: PING :cadance.canternet.org
20150614043809: input: PING :cadance.canternet.org
20150614043809: Ping Request Responded to Successfully
20150614043809: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614043809: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614044010: input: PING :cadance.canternet.org
20150614044010: input: PING :cadance.canternet.org
20150614044010: Ping Request Responded to Successfully
20150614044010: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614044010: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614044211: input: PING :cadance.canternet.org
20150614044211: input: PING :cadance.canternet.org
20150614044211: Ping Request Responded to Successfully
20150614044211: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614044211: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614044412: input: PING :cadance.canternet.org
20150614044412: input: PING :cadance.canternet.org
20150614044412: Ping Request Responded to Successfully
20150614044412: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614044412: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614044613: input: PING :cadance.canternet.org
20150614044613: input: PING :cadance.canternet.org
20150614044613: Ping Request Responded to Successfully
20150614044613: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614044613: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614044814: input: PING :cadance.canternet.org
20150614044814: input: PING :cadance.canternet.org
20150614044814: Ping Request Responded to Successfully
20150614044814: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614044814: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614045015: input: PING :cadance.canternet.org
20150614045015: input: PING :cadance.canternet.org
20150614045015: Ping Request Responded to Successfully
20150614045015: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614045015: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614045216: input: PING :cadance.canternet.org
20150614045216: input: PING :cadance.canternet.org
20150614045216: Ping Request Responded to Successfully
20150614045216: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614045216: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614045417: input: PING :cadance.canternet.org
20150614045417: input: PING :cadance.canternet.org
20150614045417: Ping Request Responded to Successfully
20150614045417: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614045417: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614045618: input: PING :cadance.canternet.org
20150614045618: input: PING :cadance.canternet.org
20150614045618: Ping Request Responded to Successfully
20150614045619: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614045619: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614045819: input: PING :cadance.canternet.org
20150614045819: input: PING :cadance.canternet.org
20150614045819: Ping Request Responded to Successfully
20150614045819: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614045819: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614050020: input: PING :cadance.canternet.org
20150614050020: input: PING :cadance.canternet.org
20150614050020: Ping Request Responded to Successfully
20150614050020: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614050020: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614050221: input: PING :cadance.canternet.org
20150614050221: input: PING :cadance.canternet.org
20150614050221: Ping Request Responded to Successfully
20150614050221: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614050221: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614050422: input: PING :cadance.canternet.org
20150614050422: input: PING :cadance.canternet.org
20150614050422: Ping Request Responded to Successfully
20150614050422: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614050422: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614050623: input: PING :cadance.canternet.org
20150614050623: input: PING :cadance.canternet.org
20150614050623: Ping Request Responded to Successfully
20150614050623: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614050623: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614050824: input: PING :cadance.canternet.org
20150614050824: input: PING :cadance.canternet.org
20150614050824: Ping Request Responded to Successfully
20150614050824: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614050824: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614051025: input: PING :cadance.canternet.org
20150614051025: input: PING :cadance.canternet.org
20150614051025: Ping Request Responded to Successfully
20150614051025: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614051025: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614051226: input: PING :cadance.canternet.org
20150614051227: input: PING :cadance.canternet.org
20150614051227: Ping Request Responded to Successfully
20150614051227: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614051227: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614051427: input: PING :cadance.canternet.org
20150614051428: input: PING :cadance.canternet.org
20150614051428: Ping Request Responded to Successfully
20150614051428: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614051429: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614051628: input: PING :cadance.canternet.org
20150614051628: input: PING :cadance.canternet.org
20150614051628: Ping Request Responded to Successfully
20150614051628: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614051628: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614051829: input: PING :cadance.canternet.org
20150614051829: input: PING :cadance.canternet.org
20150614051829: Ping Request Responded to Successfully
20150614051829: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614051829: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614052030: input: PING :cadance.canternet.org
20150614052030: input: PING :cadance.canternet.org
20150614052030: Ping Request Responded to Successfully
20150614052030: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614052030: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614052231: input: PING :cadance.canternet.org
20150614052231: input: PING :cadance.canternet.org
20150614052231: Ping Request Responded to Successfully
20150614052231: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614052231: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150614052432: input: PING :cadance.canternet.org
20150614052432: input: PING :cadance.canternet.org
20150614052432: Ping Request Responded to Successfully
20150614052432: Exception in main loop: 'NoneType' object has no attribute 'values'
20150614052432: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831102314: Establishing connection to [irc.horse]
20150831102316: :cadance.canternet.org NOTICE Auth :*** Looking up your hostname...
:cadance.canternet.org NOTICE Auth :*** Found your hostname (cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net)

20150831102317: PING :JA?y\bmw\C
:cadance.canternet.org NOTICE sleumasBot :*** If you are having problems connecting due to ping timeouts, please type /quote PONG JA?y\bmw\C or /raw PONG JA?y\bmw\C now.

20150831102317: Ping Request Responded to Successfully
20150831102317: :cadance.canternet.org NOTICE Auth :Welcome to Canternet!
:cadance.canternet.org 001 sleumasBot :Welcome to the Canternet IRC Network sleumasBot!sleumasBot@cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net
:cadance.canternet.org 002 sleumasBot :Your host is cadance.canternet.org, running version InspIRCd-2.0
:cadance.canternet.org 003 sleumasBot :This server was created 01:24:01 May 12 2015
:cadance.canternet.org 004 sleumasBot cadance.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:cadance.canternet.org 005 sleumasBot AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:cadance.canternet.org 005 sleumasBot KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150831102317: Ping Request Responded to Successfully
20150831102317: 
:cadance.canternet.org 005 sleumasBot SSL=0.0.0.0:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:cadance.canternet.org 042 sleumasBot 142AE95DH :your unique ID
:cadance.canternet.org 375 sleumasBot :cadance.canternet.org message of the day
:cadance.canternet.org 372 sleumasBot :-                                                 Y
:cadance.canternet.org 372 sleumasBot :-                                                Yj
:cadance.canternet.org 372 sleumasBot :-                                              jYY
:cadance.canternet.org 372 sleumasBot :-                                      #YYTYYYYYYaT   B
:cadance.canternet.org 372 sleumasBot :-                                   zzFYYYYY        J#a
:cadance.canternet.org 372 sleumasBot :-                                 JDsJaF     EEBBHE6YYJ Y
:cadance.canternet.org 372 sleumasBot :-                                TDTTJTJ  EHFFGFGFGFFBE  Yz
:cadance.canternet.org 372 sleumasBot :-                               7 GTGTJTLEHBFGGRGGFFFGFFE
20150831102317: 
:cadance.canternet.org 372 sleumasBot :-                               Y RTnJTJTTYYEEFFGB  HFGFFBE
:cadance.canternet.org 372 sleumasBot :-                              x  RYTTJTJTHTTYY BFLYY EHBFBE
:cadance.canternet.org 372 sleumasBot :-                              1 EHYYTTJTsa    GE ZYPEE  EHEE
:cadance.canternet.org 372 sleumasBot :-                              s HBFYYJTas    EEEEYYJ E    EE
:cadance.canternet.org 372 sleumasBot :-                              1 EFFBYTTJx   zY  E TJ E
:cadance.canternet.org 372 sleumasBot :-        7jYTYTYYYT1            Y HFFTYYJa   1  EEYT@ E
:cadance.canternet.org 372 sleumasBot :-      nYYYYYYY     YT          z  HFFHYYJ#   aY EYTT E
:cadance.canternet.org 372 sleumasBot :-    1TYYYYYY  YEEE   YY         Y YBFBHET#Y   GDsTTJTRG
:cadance.canternet.org 372 sleumasBot :-   7YYYYYY  EBFFFFBBE  YJ       7Y FFGFYTJz#x YTJTJTeTB
:cadance.canternet.org 372 sleumasBot :-   TYYYYYY EFGRRRFFFFHE  x       x  HFFYYTTaa#asJJJFJB
:cadance.canternet.org 372 sleumasBot :-  nYYYYYY 1FGDRGFBHHEBHE  5FBFY   T  FFFYTTFis1zxLB
20150831102317: 
:cadance.canternet.org 372 sleumasBot :-  1YYYYYY EFDRGBE     EEDJJJTaa#F J  BFEYTTF
:cadance.canternet.org 372 sleumasBot :-  TYYYYYY EGRRFJ       GT JTJTaJsaJ  BBYTTJ8
:cadance.canternet.org 372 sleumasBot :-  YYYYYYY EFDGB        sTTTaJJJaTa  EBEYTJTL
:cadance.canternet.org 372 sleumasBot :-  7YYYYYY 0FRRB       FsYYsJaTJTJT EBBYTJJa8
:cadance.canternet.org 372 sleumasBot :-  7YYYYYY  BGGFE      DJTTJJTJTTT EHEYTJTaJB
:cadance.canternet.org 372 sleumasBot :-   YYYYYYY EFRFB       # JsTJTTJEEYYYYTJaJs
:cadance.canternet.org 372 sleumasBot :-   jYYYYYY  FGRFL      0aaJJTRTTTTTTTJTaJzG
:cadance.canternet.org 372 sleumasBot :-    7YYYYYY EFGFE      P#JJT1TTTTTJTJTTJX
:cadance.canternet.org 372 sleumasBot :-     jYYYYY  BGGF@      JJTTeneGTJJJTTRK
:cadance.canternet.org 372 sleumasBot :-      jYYYYY EFRFE    jsaTTD71 GTTJTX7nO
:cadance.canternet.org 372 sleumasBot :-       1YYYY  FGGB   BaaTJT7xG JJaJTnj7O
:cadance.canternet.org 372 sleumasBot :-       xYYYYY BRGFE  aaTJTR1jRYJJTJTp1jjZ
:cadance.canternet.org 372 sleumasBot :-       TYYYY  BGDFH GJJaTTLj7 GJTaTTi1zjF
20150831102317: 
:cadance.canternet.org 372 sleumasBot :-       xYYYY  BRRFH FTJJJTn1X FTJTTTRzxxF
:cadance.canternet.org 372 sleumasBot :-  #TTTYYYY   EGGRBE 1JTaJs7j@ iJTJTT8x#7P
:cadance.canternet.org 372 sleumasBot :-   1YYYYY   EFGGBH  #JJTJTn1e eTJJJTRz1zjR
:cadance.canternet.org 372 sleumasBot :-     7sJYYEHFFFBE   ssJJTT571pPTTJTTT71nnF
:cadance.canternet.org 372 sleumasBot :-       EEEEEEHE     zJJTJTR1eRGTJTaTTRXX@G 
:cadance.canternet.org 372 sleumasBot :-                    ZJTJTTR8  GJTJJJTG
:cadance.canternet.org 372 sleumasBot :-                    FGTTJTF    KJTaTJTi
:cadance.canternet.org 372 sleumasBot :- 
:cadance.canternet.org 372 sleumasBot :- /---------------------------------------------------------\
:cadance.canternet.org 372 sleumasBot :- |           Welcome to canternet.org IRC!                 |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Rules: 1) No spamming/flooding                          |
20150831102318: 
:cadance.canternet.org 372 sleumasBot :- |        2) No abusive bots                               |
:cadance.canternet.org 372 sleumasBot :- | For more detailed rules, use the /rules command         |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Ports:                                                  |
:cadance.canternet.org 372 sleumasBot :- |       SSL: 6660-6665                                    |
:cadance.canternet.org 372 sleumasBot :- |       non-SSL: 6666-6669                                |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Official Channels:                                      |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- |       Lobby: #Canternet                                 |
:cadance.canternet.org 372 sleumasBot :- |       Help:  #Help                                      |
20150831102318: 
:cadance.canternet.org 372 sleumasBot :- | For other channels use /list or /msg ALIS list          |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- | Services:                                               |
:cadance.canternet.org 372 sleumasBot :- |    /msg NickServ help                                   |
:cadance.canternet.org 372 sleumasBot :- |    /msg ChanServ help                                   |
:cadance.canternet.org 372 sleumasBot :- |    /msg MemoServ help                                   |
:cadance.canternet.org 372 sleumasBot :- | For all other services: /msg HelpServ services          |
:cadance.canternet.org 372 sleumasBot :- |                                                         |
:cadance.canternet.org 372 sleumasBot :- \---------------------------------------------------------/
:cadance.canternet.org 376 sleumasBot :End of message of the day.
:cadance.canternet.org 251 sleumasBot :There are 6 users and 912 invisible on 7 servers
20150831102318: 
:cadance.canternet.org 252 sleumasBot 43 :operator(s) online
:cadance.canternet.org 253 sleumasBot 1 :unknown connections
:cadance.canternet.org 254 sleumasBot 761 :channels formed
:cadance.canternet.org 255 sleumasBot :I have 288 clients and 4 servers
:cadance.canternet.org 265 sleumasBot :Current Local Users: 288  Max: 1009
:cadance.canternet.org 266 sleumasBot :Current Global Users: 918  Max: 2151
:cadance.canternet.org 396 sleumasBot Pony-e04nim.cable.virginm.net :is now your displayed host
:sleumasBot!sleumasBot@Pony-e04nim.cable.virginm.net MODE sleumasBot +xi
:cadance.canternet.org NOTICE sleumasBot :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:cadance.canternet.org NOTICE sleumasBot :*** Forwarding PASS to NickServ

20150831102318: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** End of Message(s) of the Day ***
20150831102318: 

20150831102318: :NickServ!NickServ@canternet.org NOTICE sleumasBot :Welcome to Canternet, sleumasBot! Here on Canternet, we provide services to enable the registration of nicknames and channels! For details, type /msg NickServ help and /msg ChanServ help.
:NickServ!NickServ@canternet.org NOTICE sleumasBot :sleumasBot is not a registered nickname.

20150831102322: Connected
20150831102322: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :sleumasBot is not a registered nickname.
20150831102322: input: :sleumasBot!sleumasBot@Pony-e04nim.cable.virginm.net JOIN :#Sleu
20150831102322: input: :cadance.canternet.org 332 sleumasBot #Sleu :https://www.kickstarter.com/projects/1570995455/wubs/comments
20150831102322: input: :cadance.canternet.org 333 sleumasBot #Sleu sleumas2000!sleumie@my.little.karaoke 1439240990
20150831102322: input: :cadance.canternet.org 353 sleumasBot = #Sleu :Creeps|AFK sleumasBot ~sleumas2000 
20150831102322: input: :cadance.canternet.org 366 sleumasBot #Sleu :End of /NAMES list.
20150831102523: input: PING :cadance.canternet.org
20150831102523: input: PING :cadance.canternet.org
20150831102523: Ping Request Responded to Successfully
20150831102523: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831102523: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831102724: input: PING :cadance.canternet.org
20150831102724: input: PING :cadance.canternet.org
20150831102724: Ping Request Responded to Successfully
20150831102724: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831102724: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831102826: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :+ping sleumas2000 
20150831102830: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :+ping sleumasBot
20150831102838: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :help
20150831102846: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :!help
20150831102848: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :+help
20150831102850: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :.help
20150831102852: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :~help
20150831102908: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :|help
20150831102922: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|help
20150831102925: input: PING :cadance.canternet.org
20150831102925: input: PING :cadance.canternet.org
20150831102925: Ping Request Responded to Successfully
20150831102925: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831102925: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831103126: input: PING :cadance.canternet.org
20150831103126: input: PING :cadance.canternet.org
20150831103126: Ping Request Responded to Successfully
20150831103126: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831103126: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831103327: input: PING :cadance.canternet.org
20150831103327: input: PING :cadance.canternet.org
20150831103327: Ping Request Responded to Successfully
20150831103327: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831103327: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831103414: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|sr l
20150831103504: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|sr h
20150831103510: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG sleumasBot :|help
20150831103705: input: PING :cadance.canternet.org
20150831103705: input: PING :cadance.canternet.org
20150831103705: Ping Request Responded to Successfully
20150831103705: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831103705: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831103906: input: PING :cadance.canternet.org
20150831103906: input: PING :cadance.canternet.org
20150831103906: Ping Request Responded to Successfully
20150831103906: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831103906: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831104107: input: PING :cadance.canternet.org
20150831104107: input: PING :cadance.canternet.org
20150831104107: Ping Request Responded to Successfully
20150831104107: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831104107: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831104308: input: PING :cadance.canternet.org
20150831104308: input: PING :cadance.canternet.org
20150831104308: Ping Request Responded to Successfully
20150831104308: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831104308: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831104418: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|silent catch
20150831104438: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|h
20150831104446: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|help
20150831104505: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :--
20150831104509: input: PING :cadance.canternet.org
20150831104509: input: PING :cadance.canternet.org
20150831104509: Ping Request Responded to Successfully
20150831104509: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831104509: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831104710: input: PING :cadance.canternet.org
20150831104710: input: PING :cadance.canternet.org
20150831104710: Ping Request Responded to Successfully
20150831104710: Exception in main loop: 'NoneType' object has no attribute 'values'
20150831104710: Traceback: Traceback (most recent call last):
  File "main2.py", line 149, in main
    for t in threads.values():
AttributeError: 'NoneType' object has no attribute 'values'

20150831104748: Establishing connection to [irc.horse]
20150831104749: :discord.canternet.org NOTICE Auth :*** Looking up your hostname...
:discord.canternet.org NOTICE Auth :*** Found your hostname (cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net) -- cached

20150831104749: :discord.canternet.org 433 * sleumasBot :Nickname is already in use.

20150831104751: PING :pB\XD]epz^
:discord.canternet.org NOTICE sleumasBot_ :*** If you are having problems connecting due to ping timeouts, please type /quote PONG pB\XD]epz^ or /raw PONG pB\XD]epz^ now.

20150831104751: Ping Request Responded to Successfully
20150831104751: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831104751: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831104751: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150831104752: :discord.canternet.org NOTICE Auth :Welcome to Canternet!
:discord.canternet.org 001 sleumasBot_ :Welcome to the Canternet IRC Network sleumasBot_!sleumasBot@cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net
:discord.canternet.org 002 sleumasBot_ :Your host is discord.canternet.org, running version InspIRCd-2.0
:discord.canternet.org 003 sleumasBot_ :This server was created 09:52:30 Jun 29 2015
:discord.canternet.org 004 sleumasBot_ discord.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:discord.canternet.org 005 sleumasBot_ AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:discord.canternet.org 005 sleumasBot_ KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150831104752: Ping Request Responded to Successfully
20150831104752: 
:discord.canternet.org 005 sleumasBot_ SSL=10.48.79.180:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:discord.canternet.org 042 sleumasBot_ 787AD3RSI :your unique ID
:discord.canternet.org 375 sleumasBot_ :discord.canternet.org message of the day
:discord.canternet.org 372 sleumasBot_ :-                         .. ..                                    
:discord.canternet.org 372 sleumasBot_ :-                    ..._iauXXXXa,. .__ .                          
:discord.canternet.org 372 sleumasBot_ :-                   :-<uXXXXXZXXXZ6=+-     ._av}`                  
:discord.canternet.org 372 sleumasBot_ :-               ..:_<uXXXXXXXXXXXXXc    ._uS}" ___,.               
:discord.canternet.org 372 sleumasBot_ :-          .r  ;:.aZXXXXY!"YXXXXXXXX_==aoX2suoSo22!`               
:discord.canternet.org 372 sleumasBot_ :-       _;--L jq%?dXXX!`    {XXZXXXX>=Xooooo1"""                   
:discord.canternet.org 372 sleumasBot_ :-     _ms^ .aY"-_dmmmp3ma,..]S3XXXXXi2o22oooooo=                   
20150831104752: 
:discord.canternet.org 372 sleumasBot_ :-    <ZX6._7'.:qWBW7?' -!"^-**%||)|lvo2ooon}^~                     
:discord.canternet.org 372 sleumasBot_ :-    -ZXX2P _asmW#B(       .|+|+<isvo2o2o2}""   ._|=|__.           
:discord.canternet.org 372 sleumasBot_ :- ./3mQmWgLjWBmWX}     _   |+|+|=**n2ooo}~~   .<}+^--^+{i_.        
:discord.canternet.org 372 sleumasBot_ :- .!JDVV$W&X#mWAXs,,_s%`  =|+|+|+`   ---     .l'        -{%=.      
:discord.canternet.org 372 sleumasBot_ :-  --)lvvm#VU#Z2YSZZY"   =+|++|=`            =i;          )ia, .   
:discord.canternet.org 372 sleumasBot_ :-   .cqvIXiIznX(    _a, :|++|++`              +I,.      _asdo2( ._,
:discord.canternet.org 372 sleumasBot_ :-   -Svvoo11vXXc]#k=?$h.|+|++|=                  -~<uXmU#ZZZ#ZX7^- 
:discord.canternet.org 372 sleumasBot_ :-     "XXXXXXSS{mmZ$Z1Y|+|+|++|:                      -"""!"!!1*~- 
:discord.canternet.org 372 sleumasBot_ :-      )SX(     "4###Xt+|=<%>++`                            -1ii.  
:discord.canternet.org 372 sleumasBot_ :-   _oaoXX(   aawa>~._aawq#Z^-                              )lii.  
20150831104752: 
:discord.canternet.org 372 sleumasBot_ :-  -meSSXXo. j7^_dP?m#mZY+|;                               +2iii   
:discord.canternet.org 372 sleumasBot_ :-   ?. "?Ymc "  W[ ]#+|++|+:                              )aiii>   
:discord.canternet.org 372 sleumasBot_ :-       .jWW(   "'  ?n%+|+|:                             a%iiii`   
:discord.canternet.org 372 sleumasBot_ :-       }mWF[         |=|+|;                           _,Y|iii`    
:discord.canternet.org 372 sleumasBot_ :-       -WB `         >||+|+;                        .,)1iiii`     
:discord.canternet.org 372 sleumasBot_ :-        ^$,         uo>+<si>;                     _,]1liii>       
:discord.canternet.org 372 sleumasBot_ :-         -'        )SXouoooSc+_.       _.    _ as)1Iliii>`        
:discord.canternet.org 372 sleumasBot_ :-                   -SoXo222oo||||+||_|YY(3Y=Y1i||iiiii+`          
:discord.canternet.org 372 sleumasBot_ :-                     "{Soo2oe++++|+<liiliiiiiiiili>~-             
:discord.canternet.org 372 sleumasBot_ :-                     _Sonoe" --~-+=iiiiii||+~~~-                  
20150831104753: 
:discord.canternet.org 372 sleumasBot_ :-                     Jn~nc                                        
:discord.canternet.org 372 sleumasBot_ :-                 _wgdo( =n;                                       
:discord.canternet.org 372 sleumasBot_ :-                 !P'     I(.                                      
:discord.canternet.org 372 sleumasBot_ :-                        :===.                                     
:discord.canternet.org 372 sleumasBot_ :-                         ---                                      
:discord.canternet.org 372 sleumasBot_ :- /---------------------------------------------------------\
:discord.canternet.org 372 sleumasBot_ :- |           Welcome to canternet.org IRC!                 |
:discord.canternet.org 372 sleumasBot_ :- |           This is discord.canternet.org                 |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Rules: 1) No spamming/flooding                          |
20150831104753: 
:discord.canternet.org 372 sleumasBot_ :- |        2) No abusive bots                               |
:discord.canternet.org 372 sleumasBot_ :- | For more detailed rules, use the /rules command         |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Ports:                                                  |
:discord.canternet.org 372 sleumasBot_ :- |       SSL: 6660-6665, 6697                              |
:discord.canternet.org 372 sleumasBot_ :- |       non-SSL: 6666-6669                                |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Official Channels:                                      |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- |       Lobby: #Canternet                                 |
20150831104753: 
:discord.canternet.org 372 sleumasBot_ :- |       Help:  #Help                                      |
:discord.canternet.org 372 sleumasBot_ :- | For other channels use /list or /msg ALIS list          |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Services:                                               |
:discord.canternet.org 372 sleumasBot_ :- |    /msg NickServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- |    /msg ChanServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- |    /msg MemoServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- | For all other services: /msg HelpServ services          |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- \---------------------------------------------------------/
20150831104753: 
:discord.canternet.org 376 sleumasBot_ :End of message of the day.
:discord.canternet.org 251 sleumasBot_ :There are 6 users and 924 invisible on 7 servers
:discord.canternet.org 252 sleumasBot_ 43 :operator(s) online
:discord.canternet.org 253 sleumasBot_ 1 :unknown connections
:discord.canternet.org 254 sleumasBot_ 763 :channels formed
:discord.canternet.org 255 sleumasBot_ :I have 235 clients and 2 servers
:discord.canternet.org 265 sleumasBot_ :Current Local Users: 235  Max: 320
:discord.canternet.org 266 sleumasBot_ :Current Global Users: 930  Max: 1379
:discord.canternet.org 396 sleumasBot_ Pony-e04nim.cable.virginm.net :is now your displayed host
:sleumasBot_!sleumasBot@Pony-e04nim.cable.virginm.net MODE sleumasBot_ +xi
:discord.canternet.org NOTICE sleumasBot_ :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:discord.canternet.org NOTICE sleumasBot_ :*** Forwarding PASS to NickServ

20150831104753: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:

20150831104753: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** End of Message(s) of the Day ***
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :Welcome to Canternet, sleumasBot_! Here on Canternet, we provide services to enable the registration of nicknames and channels! For details, type /msg NickServ help and /msg ChanServ help.
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot_ is not a registered nickname.

20150831104753: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.

20150831104753: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.

20150831104754: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150831104755: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.

20150831104755: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.

20150831104755: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150831104759: Connected
20150831104803: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.
20150831104804: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.
20150831104805: input: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.
20150831104809: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot is not a registered nickname.
20150831104810: input: :sleumasBot_!sleumasBot@Pony-e04nim.cable.virginm.net JOIN :#Sleu
20150831104810: input: :discord.canternet.org 332 sleumasBot_ #Sleu :https://www.kickstarter.com/projects/1570995455/wubs/comments
20150831104810: input: :discord.canternet.org 333 sleumasBot_ #Sleu sleumas2000!sleumie@my.little.karaoke 1439240990
20150831104810: input: :discord.canternet.org 353 sleumasBot_ = #Sleu :~sleumas2000 Creeps|AFK sleumasBot sleumasBot_ 
20150831104810: input: :discord.canternet.org 366 sleumasBot_ #Sleu :End of /NAMES list.
20150831105229: Establishing connection to [irc.horse]
20150831105231: :discord.canternet.org NOTICE Auth :*** Looking up your hostname...
:discord.canternet.org NOTICE Auth :*** Found your hostname (cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net) -- cached

20150831105231: PING :ksH`[WW^yY
:discord.canternet.org NOTICE sleumasBot :*** If you are having problems connecting due to ping timeouts, please type /quote PONG ksH`[WW^yY or /raw PONG ksH`[WW^yY now.

20150831105231: Ping Request Responded to Successfully
20150831105232: :discord.canternet.org NOTICE Auth :Welcome to Canternet!
:discord.canternet.org 001 sleumasBot :Welcome to the Canternet IRC Network sleumasBot!sleumasBot@cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net
:discord.canternet.org 002 sleumasBot :Your host is discord.canternet.org, running version InspIRCd-2.0
:discord.canternet.org 003 sleumasBot :This server was created 09:52:30 Jun 29 2015
:discord.canternet.org 004 sleumasBot discord.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:discord.canternet.org 005 sleumasBot AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:discord.canternet.org 005 sleumasBot KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150831105232: Ping Request Responded to Successfully
20150831105232: 
:discord.canternet.org 005 sleumasBot SSL=10.48.79.180:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:discord.canternet.org 042 sleumasBot 787AD3RSV :your unique ID
:discord.canternet.org 375 sleumasBot :discord.canternet.org message of the day
:discord.canternet.org 372 sleumasBot :-                         .. ..                                    
:discord.canternet.org 372 sleumasBot :-                    ..._iauXXXXa,. .__ .                          
:discord.canternet.org 372 sleumasBot :-                   :-<uXXXXXZXXXZ6=+-     ._av}`                  
:discord.canternet.org 372 sleumasBot :-               ..:_<uXXXXXXXXXXXXXc    ._uS}" ___,.               
:discord.canternet.org 372 sleumasBot :-          .r  ;:.aZXXXXY!"YXXXXXXXX_==aoX2suoSo22!`               
:discord.canternet.org 372 sleumasBot :-       _;--L jq%?dXXX!`    {XXZXXXX>=Xooooo1"""                   
:discord.canternet.org 372 sleumasBot :-     _ms^ .aY"-_dmmmp3ma,..]S3XXXXXi2o22oooooo=                   
20150831105232: 
:discord.canternet.org 372 sleumasBot :-    <ZX6._7'.:qWBW7?' -!"^-**%||)|lvo2ooon}^~                     
:discord.canternet.org 372 sleumasBot :-    -ZXX2P _asmW#B(       .|+|+<isvo2o2o2}""   ._|=|__.           
:discord.canternet.org 372 sleumasBot :- ./3mQmWgLjWBmWX}     _   |+|+|=**n2ooo}~~   .<}+^--^+{i_.        
:discord.canternet.org 372 sleumasBot :- .!JDVV$W&X#mWAXs,,_s%`  =|+|+|+`   ---     .l'        -{%=.      
:discord.canternet.org 372 sleumasBot :-  --)lvvm#VU#Z2YSZZY"   =+|++|=`            =i;          )ia, .   
:discord.canternet.org 372 sleumasBot :-   .cqvIXiIznX(    _a, :|++|++`              +I,.      _asdo2( ._,
:discord.canternet.org 372 sleumasBot :-   -Svvoo11vXXc]#k=?$h.|+|++|=                  -~<uXmU#ZZZ#ZX7^- 
:discord.canternet.org 372 sleumasBot :-     "XXXXXXSS{mmZ$Z1Y|+|+|++|:                      -"""!"!!1*~- 
:discord.canternet.org 372 sleumasBot :-      )SX(     "4###Xt+|=<%>++`                            -1ii.  
:discord.canternet.org 372 sleumasBot :-   _oaoXX(   aawa>~._aawq#Z^-                              )lii.  
20150831105232: 
:discord.canternet.org 372 sleumasBot :-  -meSSXXo. j7^_dP?m#mZY+|;                               +2iii   
:discord.canternet.org 372 sleumasBot :-   ?. "?Ymc "  W[ ]#+|++|+:                              )aiii>   
:discord.canternet.org 372 sleumasBot :-       .jWW(   "'  ?n%+|+|:                             a%iiii`   
:discord.canternet.org 372 sleumasBot :-       }mWF[         |=|+|;                           _,Y|iii`    
:discord.canternet.org 372 sleumasBot :-       -WB `         >||+|+;                        .,)1iiii`     
:discord.canternet.org 372 sleumasBot :-        ^$,         uo>+<si>;                     _,]1liii>       
:discord.canternet.org 372 sleumasBot :-         -'        )SXouoooSc+_.       _.    _ as)1Iliii>`        
:discord.canternet.org 372 sleumasBot :-                   -SoXo222oo||||+||_|YY(3Y=Y1i||iiiii+`          
:discord.canternet.org 372 sleumasBot :-                     "{Soo2oe++++|+<liiliiiiiiiili>~-             
:discord.canternet.org 372 sleumasBot :-                     _Sonoe" --~-+=iiiiii||+~~~-                  
20150831105232: 
:discord.canternet.org 372 sleumasBot :-                     Jn~nc                                        
:discord.canternet.org 372 sleumasBot :-                 _wgdo( =n;                                       
:discord.canternet.org 372 sleumasBot :-                 !P'     I(.                                      
:discord.canternet.org 372 sleumasBot :-                        :===.                                     
:discord.canternet.org 372 sleumasBot :-                         ---                                      
:discord.canternet.org 372 sleumasBot :- /---------------------------------------------------------\
:discord.canternet.org 372 sleumasBot :- |           Welcome to canternet.org IRC!                 |
:discord.canternet.org 372 sleumasBot :- |           This is discord.canternet.org                 |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- | Rules: 1) No spamming/flooding                          |
20150831105232: 
:discord.canternet.org 372 sleumasBot :- |        2) No abusive bots                               |
:discord.canternet.org 372 sleumasBot :- | For more detailed rules, use the /rules command         |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- | Ports:                                                  |
:discord.canternet.org 372 sleumasBot :- |       SSL: 6660-6665, 6697                              |
:discord.canternet.org 372 sleumasBot :- |       non-SSL: 6666-6669                                |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- | Official Channels:                                      |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- |       Lobby: #Canternet                                 |
:discord.canternet.org 372 sleumasBot :- |       Help:  #Help                                      |
20150831105232: 
:discord.canternet.org 372 sleumasBot :- | For other channels use /list or /msg ALIS list          |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- | Services:                                               |
:discord.canternet.org 372 sleumasBot :- |    /msg NickServ help                                   |
:discord.canternet.org 372 sleumasBot :- |    /msg ChanServ help                                   |
:discord.canternet.org 372 sleumasBot :- |    /msg MemoServ help                                   |
:discord.canternet.org 372 sleumasBot :- | For all other services: /msg HelpServ services          |
:discord.canternet.org 372 sleumasBot :- |                                                         |
:discord.canternet.org 372 sleumasBot :- \---------------------------------------------------------/
:discord.canternet.org 376 sleumasBot :End of message of the day.
:discord.canternet.org 251 sleumasBot :There are 6 users and 915 invisible on 7 servers
20150831105233: 
:discord.canternet.org 252 sleumasBot 43 :operator(s) online
:discord.canternet.org 254 sleumasBot 763 :channels formed
:discord.canternet.org 255 sleumasBot :I have 234 clients and 2 servers
:discord.canternet.org 265 sleumasBot :Current Local Users: 234  Max: 320
:discord.canternet.org 266 sleumasBot :Current Global Users: 921  Max: 1379
:discord.canternet.org 396 sleumasBot Pony-e04nim.cable.virginm.net :is now your displayed host
:sleumasBot!sleumasBot@Pony-e04nim.cable.virginm.net MODE sleumasBot +xi
:discord.canternet.org NOTICE sleumasBot :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:discord.canternet.org NOTICE sleumasBot :*** Forwarding PASS to NickServ

20150831105233: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot :*** End of Message(s) of the Day ***
20150831105233: 

20150831105233: :NickServ!NickServ@canternet.org NOTICE sleumasBot :This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
:NickServ!NickServ@canternet.org NOTICE sleumasBot :You have 30 seconds to identify to your nickname before it is changed.
:NickServ!NickServ@canternet.org NOTICE sleumasBot :You are now identified for sleumas2000.
:discord.canternet.org 900 sleumasBot sleumasBot!sleumasBot@Pony-e04nim.cable.virginm.net sleumas2000 :You are now logged in as sleumas2000
:discord.canternet.org MODE sleumasBot -x
:discord.canternet.org 396 sleumasBot my.little.karaoke :is now your displayed host

20150831105236: Connected
20150831105236: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :You are already logged in as sleumas2000.
20150831105236: input: :sleumasBot!sleumasBot@my.little.karaoke JOIN :#Sleu
20150831105236: input: :discord.canternet.org 332 sleumasBot #Sleu :https://www.kickstarter.com/projects/1570995455/wubs/comments
20150831105236: input: :discord.canternet.org 333 sleumasBot #Sleu sleumas2000!sleumie@my.little.karaoke 1439240990
20150831105236: input: :discord.canternet.org 353 sleumasBot = #Sleu :~sleumas2000 Creeps|AFK sleumasBot 
20150831105236: input: :discord.canternet.org 366 sleumasBot #Sleu :End of /NAMES list.
20150831105236: input: :ChanServ!ChanServ@canternet.org MODE #Sleu +qo sleumasBot sleumasBot
20150831105252: input: :sleumas2000!sleumas2000@my.little.karaoke PRIVMSG #Sleu :|help
20150831105342: Establishing connection to [irc.horse]
20150831105343: :discord.canternet.org NOTICE Auth :*** Looking up your hostname...
:discord.canternet.org NOTICE Auth :*** Found your hostname (cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net) -- cached

20150831105343: :discord.canternet.org 433 * sleumasBot :Nickname is already in use.

20150831105437: input: PING :discord.canternet.org
20150831105437: input: PING :discord.canternet.org
20150831105437: Ping Request Responded to Successfully
20150831105448: Establishing connection to [irc.horse]
20150831105450: :discord.canternet.org NOTICE Auth :*** Looking up your hostname...
:discord.canternet.org NOTICE Auth :*** Found your hostname (cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net) -- cached

20150831105450: :discord.canternet.org 433 * sleumasBot :Nickname is already in use.

20150831105451: PING :oPcOx}oMY]
:discord.canternet.org NOTICE sleumasBot_ :*** If you are having problems connecting due to ping timeouts, please type /quote PONG oPcOx}oMY] or /raw PONG oPcOx}oMY] now.

20150831105451: Ping Request Responded to Successfully
20150831105451: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831105451: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831105451: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150831105452: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831105453: :discord.canternet.org 451 sleumasBot_ PRIVMSG :You have not registered

20150831105453: :discord.canternet.org NOTICE Auth :Welcome to Canternet!
:discord.canternet.org 001 sleumasBot_ :Welcome to the Canternet IRC Network sleumasBot_!sleumasBot@cpc24-rdng21-2-0-cust118.15-3.cable.virginm.net
:discord.canternet.org 002 sleumasBot_ :Your host is discord.canternet.org, running version InspIRCd-2.0
:discord.canternet.org 003 sleumasBot_ :This server was created 09:52:30 Jun 29 2015
:discord.canternet.org 004 sleumasBot_ discord.canternet.org InspIRCd-2.0 BIRSWcdghiorswx ABCDFHIJKLMNOPQRSTXYabcdefghijklmnopqrstuvz FHIJLXYabdefghjkloqv
:discord.canternet.org 005 sleumasBot_ AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbeg,k,FHJLdfjl,ABCDKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
:discord.canternet.org 005 sleumasBot_ KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=128 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Canternet NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ SILENCE=32 :are supported by this server
20150831105453: Ping Request Responded to Successfully
20150831105453: 
:discord.canternet.org 005 sleumasBot_ SSL=10.48.79.180:6659 STARTTLS STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
:discord.canternet.org 042 sleumasBot_ 787AD3RS7 :your unique ID
:discord.canternet.org 375 sleumasBot_ :discord.canternet.org message of the day
:discord.canternet.org 372 sleumasBot_ :-                         .. ..                                    
:discord.canternet.org 372 sleumasBot_ :-                    ..._iauXXXXa,. .__ .                          
:discord.canternet.org 372 sleumasBot_ :-                   :-<uXXXXXZXXXZ6=+-     ._av}`                  
:discord.canternet.org 372 sleumasBot_ :-               ..:_<uXXXXXXXXXXXXXc    ._uS}" ___,.               
:discord.canternet.org 372 sleumasBot_ :-          .r  ;:.aZXXXXY!"YXXXXXXXX_==aoX2suoSo22!`               
:discord.canternet.org 372 sleumasBot_ :-       _;--L jq%?dXXX!`    {XXZXXXX>=Xooooo1"""                   
:discord.canternet.org 372 sleumasBot_ :-     _ms^ .aY"-_dmmmp3ma,..]S3XXXXXi2o22oooooo=                   
20150831105453: 
:discord.canternet.org 372 sleumasBot_ :-    <ZX6._7'.:qWBW7?' -!"^-**%||)|lvo2ooon}^~                     
:discord.canternet.org 372 sleumasBot_ :-    -ZXX2P _asmW#B(       .|+|+<isvo2o2o2}""   ._|=|__.           
:discord.canternet.org 372 sleumasBot_ :- ./3mQmWgLjWBmWX}     _   |+|+|=**n2ooo}~~   .<}+^--^+{i_.        
:discord.canternet.org 372 sleumasBot_ :- .!JDVV$W&X#mWAXs,,_s%`  =|+|+|+`   ---     .l'        -{%=.      
:discord.canternet.org 372 sleumasBot_ :-  --)lvvm#VU#Z2YSZZY"   =+|++|=`            =i;          )ia, .   
:discord.canternet.org 372 sleumasBot_ :-   .cqvIXiIznX(    _a, :|++|++`              +I,.      _asdo2( ._,
:discord.canternet.org 372 sleumasBot_ :-   -Svvoo11vXXc]#k=?$h.|+|++|=                  -~<uXmU#ZZZ#ZX7^- 
:discord.canternet.org 372 sleumasBot_ :-     "XXXXXXSS{mmZ$Z1Y|+|+|++|:                      -"""!"!!1*~- 
:discord.canternet.org 372 sleumasBot_ :-      )SX(     "4###Xt+|=<%>++`                            -1ii.  
:discord.canternet.org 372 sleumasBot_ :-   _oaoXX(   aawa>~._aawq#Z^-                              )lii.  
20150831105453: 
:discord.canternet.org 372 sleumasBot_ :-  -meSSXXo. j7^_dP?m#mZY+|;                               +2iii   
:discord.canternet.org 372 sleumasBot_ :-   ?. "?Ymc "  W[ ]#+|++|+:                              )aiii>   
:discord.canternet.org 372 sleumasBot_ :-       .jWW(   "'  ?n%+|+|:                             a%iiii`   
:discord.canternet.org 372 sleumasBot_ :-       }mWF[         |=|+|;                           _,Y|iii`    
:discord.canternet.org 372 sleumasBot_ :-       -WB `         >||+|+;                        .,)1iiii`     
:discord.canternet.org 372 sleumasBot_ :-        ^$,         uo>+<si>;                     _,]1liii>       
:discord.canternet.org 372 sleumasBot_ :-         -'        )SXouoooSc+_.       _.    _ as)1Iliii>`        
:discord.canternet.org 372 sleumasBot_ :-                   -SoXo222oo||||+||_|YY(3Y=Y1i||iiiii+`          
:discord.canternet.org 372 sleumasBot_ :-                     "{Soo2oe++++|+<liiliiiiiiiili>~-             
:discord.canternet.org 372 sleumasBot_ :-                     _Sonoe" --~-+=iiiiii||+~~~-                  
20150831105453: 
:discord.canternet.org 372 sleumasBot_ :-                     Jn~nc                                        
:discord.canternet.org 372 sleumasBot_ :-                 _wgdo( =n;                                       
:discord.canternet.org 372 sleumasBot_ :-                 !P'     I(.                                      
:discord.canternet.org 372 sleumasBot_ :-                        :===.                                     
:discord.canternet.org 372 sleumasBot_ :-                         ---                                      
:discord.canternet.org 372 sleumasBot_ :- /---------------------------------------------------------\
:discord.canternet.org 372 sleumasBot_ :- |           Welcome to canternet.org IRC!                 |
:discord.canternet.org 372 sleumasBot_ :- |           This is discord.canternet.org                 |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Rules: 1) No spamming/flooding                          |
20150831105453: 
:discord.canternet.org 372 sleumasBot_ :- |        2) No abusive bots                               |
:discord.canternet.org 372 sleumasBot_ :- | For more detailed rules, use the /rules command         |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Ports:                                                  |
:discord.canternet.org 372 sleumasBot_ :- |       SSL: 6660-6665, 6697                              |
:discord.canternet.org 372 sleumasBot_ :- |       non-SSL: 6666-6669                                |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Official Channels:                                      |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- |       Lobby: #Canternet                                 |
20150831105453: 
:discord.canternet.org 372 sleumasBot_ :- |       Help:  #Help                                      |
:discord.canternet.org 372 sleumasBot_ :- | For other channels use /list or /msg ALIS list          |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- | Services:                                               |
:discord.canternet.org 372 sleumasBot_ :- |    /msg NickServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- |    /msg ChanServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- |    /msg MemoServ help                                   |
:discord.canternet.org 372 sleumasBot_ :- | For all other services: /msg HelpServ services          |
:discord.canternet.org 372 sleumasBot_ :- |                                                         |
:discord.canternet.org 372 sleumasBot_ :- \---------------------------------------------------------/
20150831105454: 
:discord.canternet.org 376 sleumasBot_ :End of message of the day.
:discord.canternet.org 251 sleumasBot_ :There are 6 users and 918 invisible on 7 servers
:discord.canternet.org 252 sleumasBot_ 43 :operator(s) online
:discord.canternet.org 254 sleumasBot_ 763 :channels formed
:discord.canternet.org 255 sleumasBot_ :I have 239 clients and 2 servers
:discord.canternet.org 265 sleumasBot_ :Current Local Users: 239  Max: 320
:discord.canternet.org 266 sleumasBot_ :Current Global Users: 924  Max: 1379
:discord.canternet.org 396 sleumasBot_ Pony-e04nim.cable.virginm.net :is now your displayed host
:sleumasBot_!sleumasBot@Pony-e04nim.cable.virginm.net MODE sleumasBot_ +xi
:discord.canternet.org NOTICE sleumasBot_ :*** You are connected using SSL cipher "DHE-RSA-AES-256-CBC-SHA1"
:discord.canternet.org NOTICE sleumasBot_ :*** Forwarding PASS to NickServ

20150831105454: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** Message(s) of the Day ***
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Hotmail] Notice from Colgate, posted 05:07 on 10/19/2014:
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :Currently hotmail, livee, and outlook are blocking our emails. We are working with getting ourselves unblocked(again), but in the meantime, please do not use an email address associated with Microsoft for registration.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :[Tor] Notice from Colgate, posted 00:21 on 10/01/2014:

20150831105454: :InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :We offer a tor hidden server to connect to. In order to connect you MUST have a nickserv account and your client MUST support sasl authentication. To connect, point your client at your Tor installation and use canternet7qgrnu4.onion as the IP. On connection, your hostname will be set to @tor.sasl.youraccount or your vhost if you have one.
:InfoServ!InfoServ@canternet.org NOTICE sleumasBot_ :*** End of Message(s) of the Day ***
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :Welcome to Canternet, sleumasBot_! Here on Canternet, we provide services to enable the registration of nicknames and channels! For details, type /msg NickServ help and /msg ChanServ help.
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot_ is not a registered nickname.

20150831105454: :discord.canternet.org 433 sleumasBot_ sleumasBot :Nickname is already in use.

20150831105454: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :sleumasBot_!sleumasBot@Pony-e04nim.cable.virginm.net has just authenticated as you (sleumas2000)
20150831105454: Link Closed. Reason: :NickServ!NickServ@canternet.org killed connection because :discord.canternet.org!canternet.org!NickServ (Killed (NickServ (GHOST command used by sleumasBot_)))
20150831105455: :NickServ!NickServ@canternet.org NOTICE sleumasBot_ :You are now identified for sleumas2000.
:discord.canternet.org 900 sleumasBot_ sleumasBot_!sleumasBot@Pony-e04nim.cable.virginm.net sleumas2000 :You are now logged in as sleumas2000
:discord.canternet.org MODE sleumasBot_ -x
:discord.canternet.org 396 sleumasBot_ my.little.karaoke :is now your displayed host
:NickServ!NickServ@canternet.org NOTICE sleumasBot_ :sleumasBot has been ghosted.

20150831105455: :sleumasBot_!sleumasBot@my.little.karaoke NICK sleumasBot

20150831105456: Connected
20150831105458: input: :NickServ!NickServ@canternet.org NOTICE sleumasBot :You are already logged in as sleumas2000.
20150831105459: input: :sleumasBot!sleumasBot@my.little.karaoke JOIN :#Sleu
20150831105459: input: :discord.canternet.org 332 sleumasBot #Sleu :https://www.kickstarter.com/projects/1570995455/wubs/comments
20150831105459: input: :discord.canternet.org 333 sleumasBot #Sleu sleumas2000!sleumie@my.little.karaoke 1439240990
20150831105459: input: :discord.canternet.org 353 sleumasBot = #Sleu :~sleumas2000 Creeps|AFK sleumasBot 
20150831105459: input: :discord.canternet.org 366 sleumasBot #Sleu :End of /NAMES list.
20150831105459: input: :ChanServ!ChanServ@canternet.org MODE #Sleu +qo sleumasBot sleumasBot
20150831105700: input: PING :discord.canternet.org
20150831105700: input: PING :discord.canternet.org
20150831105700: Ping Request Responded to Successfully
20150831105901: input: PING :discord.canternet.org
20150831105901: input: PING :discord.canternet.org
20150831105901: Ping Request Responded to Successfully
20150831110102: input: PING :discord.canternet.org
20150831110102: input: PING :discord.canternet.org
20150831110102: Ping Request Responded to Successfully
20150831110303: input: PING :discord.canternet.org
20150831110303: input: PING :discord.canternet.org
20150831110303: Ping Request Responded to Successfully
20150831110504: input: PING :discord.canternet.org
20150831110504: input: PING :discord.canternet.org
20150831110504: Ping Request Responded to Successfully
20150831110705: input: PING :discord.canternet.org
20150831110705: input: PING :discord.canternet.org
20150831110705: Ping Request Responded to Successfully
20150831110906: input: PING :discord.canternet.org
20150831110906: input: PING :discord.canternet.org
20150831110906: Ping Request Responded to Successfully
20150831111107: input: PING :discord.canternet.org
20150831111107: input: PING :discord.canternet.org
20150831111107: Ping Request Responded to Successfully
20150831111308: input: PING :discord.canternet.org
20150831111308: input: PING :discord.canternet.org
20150831111308: Ping Request Responded to Successfully
20150831111509: input: PING :discord.canternet.org
20150831111509: input: PING :discord.canternet.org
20150831111509: Ping Request Responded to Successfully
20150831111710: input: PING :discord.canternet.org
20150831111710: input: PING :discord.canternet.org
20150831111710: Ping Request Responded to Successfully
20150831111911: input: PING :discord.canternet.org
20150831111911: input: PING :discord.canternet.org
20150831111911: Ping Request Responded to Successfully
20150831112112: input: PING :discord.canternet.org
20150831112112: input: PING :discord.canternet.org
20150831112112: Ping Request Responded to Successfully
20150831112313: input: PING :discord.canternet.org
20150831112313: input: PING :discord.canternet.org
20150831112313: Ping Request Responded to Successfully
20150831112514: input: PING :discord.canternet.org
20150831112514: input: PING :discord.canternet.org
20150831112514: Ping Request Responded to Successfully
20150831112715: input: PING :discord.canternet.org
20150831112715: input: PING :discord.canternet.org
20150831112715: Ping Request Responded to Successfully
20150831112916: input: PING :discord.canternet.org
20150831112916: input: PING :discord.canternet.org
20150831112916: Ping Request Responded to Successfully
20150831113117: input: PING :discord.canternet.org
20150831113117: input: PING :discord.canternet.org
20150831113117: Ping Request Responded to Successfully
20150831113318: input: PING :discord.canternet.org
20150831113318: input: PING :discord.canternet.org
20150831113318: Ping Request Responded to Successfully
20150831113519: input: PING :discord.canternet.org
20150831113519: input: PING :discord.canternet.org
20150831113519: Ping Request Responded to Successfully
20150831113720: input: PING :discord.canternet.org
20150831113720: input: PING :discord.canternet.org
20150831113720: Ping Request Responded to Successfully
